# autogenerated by ssc-gen. DO NOT EDIT
"""
Example REST API client config using DummyJSON (https://dummyjson.com).

Why DummyJSON:
  - Live, stable, no auth, no rate limits
  - Returns structured JSON error bodies: {"message": "..."}
  - Pagination (?limit=&skip=), search (?q=), nested objects — exercises
    typed/optional/array placeholders end-to-end
  - See https://dummyjson.com/docs for full surface

Equivalent alternatives you can retarget by swapping host/paths:
  - https://jsonplaceholder.typicode.com — simpler resources (posts, users,
    comments), but 404 body is empty `{}` so @error becomes formal
  - https://reqres.in — good for POST/PUT/DELETE demos with bodies
  - https://httpbin.org — request-echo, useful for HTTP mechanics only
"""
import json
import re
import sys
from typing import TypedDict, Optional, Any, List, Dict, Union
from html import unescape as _html_unescape
from bs4 import BeautifulSoup, ResultSet, Tag
BS4_FEATURES = 'lxml'
import httpx
_RE_HEX_ENTITY = re.compile(r'&#x([0-9a-fA-F]+);')
_RE_UNICODE_ENTITY = re.compile(r'\\u([0-9a-fA-F]{4})')
_RE_BYTES_ENTITY = re.compile(r'\\x([0-9a-fA-F]{2})')
_RE_CHARS_MAP = {'\b': '\b', '\f': '\f', '\n': '\n', '\r': '\r', '\t': '\t'}


def repl_map(s: str, rmap: Dict[str, str]) -> str:
    for k, v in rmap.items():
        s = s.replace(k, v)
    return s


def normalize_text(text: str) -> str:
    return ' '.join(text.split()) if text else ""


class _UnmatchedTableRow:
    pass


def unescape_text(text: str) -> str:
    s = _html_unescape(text)
    s = _RE_HEX_ENTITY.sub(lambda m: chr(int(m.group(1), 16)), s)
    s = _RE_UNICODE_ENTITY.sub(lambda m: chr(int(m.group(1), 16)), s)
    s = _RE_BYTES_ENTITY.sub(lambda m: chr(int(m.group(1), 16)), s)
    for ch, r in _RE_CHARS_MAP.items():
        s = s.replace(ch, r)
    return s


if sys.version_info >= (3, 9):
    def rm_prefix(s: str, p: str) -> str:
        return s.removeprefix(p)


    def rm_suffix(s: str, p: str) -> str:
        return s.removesuffix(p)


else:
    def rm_prefix(s: str, p: str) -> str:
        return s[len(p):] if s.startswith(p) else s


    def rm_suffix(s: str, p: str) -> str:
        return s[:-(len(p))] if s.endswith(p) else s



UNMATCHED_TABLE_ROW = _UnmatchedTableRow()



class RestApiError(Exception):
    def __init__(self, status: int, payload: Any):
        self.status = status
        self.payload = payload
        super().__init__(f'REST API error {status}: {payload!r}')



DimensionsJson = TypedDict("DimensionsJson", {
'width': float, 
'height': float, 
'depth': float, 
})
MetaJson = TypedDict("MetaJson", {
'createdAt': str, 
'updatedAt': str, 
'barcode': str, 
'qrCode': str, 
})
ReviewJson = TypedDict("ReviewJson", {
'rating': int, 
'comment': str, 
'date': str, 
'reviewerName': str, 
'reviewerEmail': str, 
})
ProductJson = TypedDict("ProductJson", {
'id': int, 
'title': str, 
'description': str, 
'category': str, 
'price': float, 
'discountPercentage': float, 
'rating': float, 
'stock': int, 
'tags': List[str], 
'brand': Optional[str], 
'sku': str, 
'weight': float, 
'dimensions': DimensionsJson, 
'warrantyInformation': str, 
'shippingInformation': str, 
'availabilityStatus': str, 
'reviews': List[ReviewJson], 
'returnPolicy': str, 
'minimumOrderQuantity': int, 
'meta': MetaJson, 
'images': List[str], 
'thumbnail': str, 
})
ProductListJson = TypedDict("ProductListJson", {
'products': List[ProductJson], 
'total': int, 
'skip': int, 
'limit': int, 
})
CategoryInfoJson = TypedDict("CategoryInfoJson", {
'slug': str, 
'name': str, 
'url': str, 
})
ApiErrorJson = TypedDict("ApiErrorJson", {
'message': str, 
})
class DummyJsonApi:
    """
    
        DummyJSON Products API client.
    
        Generated methods (Python, with --http-client requests):
            get_product(client, *, id)
            list_products(client, *, limit=None, skip=None, select=None)
            search_products(client, *, query, limit=None)
            products_by_category(client, *, category)
            list_categories(client)
            create_product(client, *, title, price, stock)
    
        NOTE: DummyJSON's POST /products/add simulates creation (the new record
        is NOT persisted server-side) — useful for testing request-body shape.
        
    """
    @classmethod
    def get_product(cls, client: httpx.Client, *, id: int) -> ProductJson:
        """Fetch one product by id."""
        _resp = client.request(
            'GET',
            f"https://dummyjson.com/products/{id}",
            headers={'Accept': 'application/json'},
        )
        _status = _resp.status_code
        try:
            _body = _resp.json()
        except Exception:
            _body = None
        if not (200 <= _status < 300):
            if _status == 404:
                raise RestApiError(_status, _body)
            _resp.raise_for_status()
        return _body
    @classmethod
    async def async_get_product(cls, client: httpx.AsyncClient, *, id: int) -> ProductJson:
        """Fetch one product by id."""
        _resp = await client.request(
            'GET',
            f"https://dummyjson.com/products/{id}",
            headers={'Accept': 'application/json'},
        )
        _status = _resp.status_code
        try:
            _body = _resp.json()
        except Exception:
            _body = None
        if not (200 <= _status < 300):
            if _status == 404:
                raise RestApiError(_status, _body)
            _resp.raise_for_status()
        return _body
    @classmethod
    def list_products(cls, client: httpx.Client, *, limit: int | None = None, skip: int | None = None, select: list[str] | None = None) -> ProductListJson:
        """Paginated product list. All params optional."""
        _params: dict = {}
        if limit is not None:
            _params['limit'] = limit
        if skip is not None:
            _params['skip'] = skip
        if select is not None:
            _params['select'] = ','.join(str(_x) for _x in select)
        _resp = client.request(
            'GET',
            'https://dummyjson.com/products',
            headers={'Accept': 'application/json'},
            params=_params,
        )
        _status = _resp.status_code
        try:
            _body = _resp.json()
        except Exception:
            _body = None
        if not (200 <= _status < 300):
            if _status == 404:
                raise RestApiError(_status, _body)
            _resp.raise_for_status()
        return _body
    @classmethod
    async def async_list_products(cls, client: httpx.AsyncClient, *, limit: int | None = None, skip: int | None = None, select: list[str] | None = None) -> ProductListJson:
        """Paginated product list. All params optional."""
        _params: dict = {}
        if limit is not None:
            _params['limit'] = limit
        if skip is not None:
            _params['skip'] = skip
        if select is not None:
            _params['select'] = ','.join(str(_x) for _x in select)
        _resp = await client.request(
            'GET',
            'https://dummyjson.com/products',
            headers={'Accept': 'application/json'},
            params=_params,
        )
        _status = _resp.status_code
        try:
            _body = _resp.json()
        except Exception:
            _body = None
        if not (200 <= _status < 300):
            if _status == 404:
                raise RestApiError(_status, _body)
            _resp.raise_for_status()
        return _body
    @classmethod
    def search_products(cls, client: httpx.Client, *, query: str, limit: int | None = None) -> ProductListJson:
        """Full-text search."""
        _params: dict = {}
        _params['q'] = query
        if limit is not None:
            _params['limit'] = limit
        _resp = client.request(
            'GET',
            'https://dummyjson.com/products/search',
            headers={'Accept': 'application/json'},
            params=_params,
        )
        _status = _resp.status_code
        try:
            _body = _resp.json()
        except Exception:
            _body = None
        if not (200 <= _status < 300):
            if _status == 404:
                raise RestApiError(_status, _body)
            _resp.raise_for_status()
        return _body
    @classmethod
    async def async_search_products(cls, client: httpx.AsyncClient, *, query: str, limit: int | None = None) -> ProductListJson:
        """Full-text search."""
        _params: dict = {}
        _params['q'] = query
        if limit is not None:
            _params['limit'] = limit
        _resp = await client.request(
            'GET',
            'https://dummyjson.com/products/search',
            headers={'Accept': 'application/json'},
            params=_params,
        )
        _status = _resp.status_code
        try:
            _body = _resp.json()
        except Exception:
            _body = None
        if not (200 <= _status < 300):
            if _status == 404:
                raise RestApiError(_status, _body)
            _resp.raise_for_status()
        return _body
    @classmethod
    def products_by_category(cls, client: httpx.Client, *, category: str) -> ProductListJson:
        """List products in a category (slug)."""
        _resp = client.request(
            'GET',
            f"https://dummyjson.com/products/category/{category}",
            headers={'Accept': 'application/json'},
        )
        _status = _resp.status_code
        try:
            _body = _resp.json()
        except Exception:
            _body = None
        if not (200 <= _status < 300):
            if _status == 404:
                raise RestApiError(_status, _body)
            _resp.raise_for_status()
        return _body
    @classmethod
    async def async_products_by_category(cls, client: httpx.AsyncClient, *, category: str) -> ProductListJson:
        """List products in a category (slug)."""
        _resp = await client.request(
            'GET',
            f"https://dummyjson.com/products/category/{category}",
            headers={'Accept': 'application/json'},
        )
        _status = _resp.status_code
        try:
            _body = _resp.json()
        except Exception:
            _body = None
        if not (200 <= _status < 300):
            if _status == 404:
                raise RestApiError(_status, _body)
            _resp.raise_for_status()
        return _body
    @classmethod
    def list_categories(cls, client: httpx.Client) -> CategoryInfoJson:
        """All available category slugs with metadata."""
        _resp = client.request(
            'GET',
            'https://dummyjson.com/products/categories',
            headers={'Accept': 'application/json'},
        )
        _status = _resp.status_code
        try:
            _body = _resp.json()
        except Exception:
            _body = None
        if not (200 <= _status < 300):
            if _status == 404:
                raise RestApiError(_status, _body)
            _resp.raise_for_status()
        return _body
    @classmethod
    async def async_list_categories(cls, client: httpx.AsyncClient) -> CategoryInfoJson:
        """All available category slugs with metadata."""
        _resp = await client.request(
            'GET',
            'https://dummyjson.com/products/categories',
            headers={'Accept': 'application/json'},
        )
        _status = _resp.status_code
        try:
            _body = _resp.json()
        except Exception:
            _body = None
        if not (200 <= _status < 300):
            if _status == 404:
                raise RestApiError(_status, _body)
            _resp.raise_for_status()
        return _body
    @classmethod
    def create_product(cls, client: httpx.Client, *, title: str, price: float, stock: int) -> ProductJson:
        """Simulated product creation (not persisted)."""
        _resp = client.request(
            'POST',
            'https://dummyjson.com/products/add',
            headers={'Content-Type': 'application/json', 'Accept': 'application/json'},
            json=f'{{"title": "{title}", "price": {price}, "stock": {stock}}}',
        )
        _status = _resp.status_code
        try:
            _body = _resp.json()
        except Exception:
            _body = None
        if not (200 <= _status < 300):
            if _status == 404:
                raise RestApiError(_status, _body)
            _resp.raise_for_status()
        return _body
    @classmethod
    async def async_create_product(cls, client: httpx.AsyncClient, *, title: str, price: float, stock: int) -> ProductJson:
        """Simulated product creation (not persisted)."""
        _resp = await client.request(
            'POST',
            'https://dummyjson.com/products/add',
            headers={'Content-Type': 'application/json', 'Accept': 'application/json'},
            json=f'{{"title": "{title}", "price": {price}, "stock": {stock}}}',
        )
        _status = _resp.status_code
        try:
            _body = _resp.json()
        except Exception:
            _body = None
        if not (200 <= _status < 300):
            if _status == 404:
                raise RestApiError(_status, _body)
            _resp.raise_for_status()
        return _body