// autogenerated by ssc-gen DO NOT_EDIT
/***
 *
 * {
 *     "f": "String"
 * }*/
class T {
    constructor(doc) {
        if (typeof doc === 'string') {
            this._doc = new DOMParser().parseFromString(doc, 'text/html');
        } else if (doc instanceof Document || doc instanceof Element) {
            this._doc = doc;
        } else {
            throw new Error(
                'Invalid input: Expected a Document, Element, or string',
            );
        }
    }

    _parseF(v) {
        let v0 = v.querySelector('#regform');

        return typeof v0.textContent === 'undefined'
            ? v0.documentElement.textContent
            : v0.textContent;
    }
    parse() {
        return {
            f: this._parseF(this._doc),
        };
    }
}
