"""Assembly of the separate runtime module file (``--separate-runtime`` / ``-R``)."""

from __future__ import annotations

from collections.abc import Callable
from typing import Any

import ssc_codegen.ast as a

from ssc_codegen.targets.python.http_libs.base import HttpLibStrategy
from ssc_codegen.targets.python.http_libs.httpx import HttpxStrategy
from ssc_codegen.traversal.utils import module_has_rest

_BASE_UTILITY_LINES: list[str] = [
    "_RE_HEX_ENTITY = re.compile(r'&#x([0-9a-fA-F]+);')",
    "_RE_UNICODE_ENTITY = re.compile(r'\\\\u([0-9a-fA-F]{4})')",
    "_RE_BYTES_ENTITY = re.compile(r'\\\\x([0-9a-fA-F]{2})')",
    "_RE_CHARS_MAP = {'\\\\b': '\\b', '\\\\f': '\\f', '\\\\n': '\\n', '\\\\r': '\\r', '\\\\t': '\\t'}",
    "",
    "def repl_map(s: str, rmap: Dict[str, str]) -> str:",
    "    for k, v in rmap.items():",
    "        s = s.replace(k, v)",
    "    return s",
    "",
    "def normalize_text(text: str) -> str:",
    "    return ' '.join(text.split()) if text else \"\"",
    "",
    "class UnmatchedTableRow:",
    "    pass",
    "",
    "def unescape_text(text: str) -> str:",
    "    s = ssc_html_unescape(text)",
    "    s = _RE_HEX_ENTITY.sub(lambda m: chr(int(m.group(1), 16)), s)",
    "    s = _RE_UNICODE_ENTITY.sub(lambda m: chr(int(m.group(1), 16)), s)",
    "    s = _RE_BYTES_ENTITY.sub(lambda m: chr(int(m.group(1), 16)), s)",
    "    for ch, r in _RE_CHARS_MAP.items():",
    "        s = s.replace(ch, r)",
    "    return s",
    "",
    "if sys.version_info >= (3, 9):",
    "    def rm_prefix(s: str, p: str) -> str:",
    "        return s.removeprefix(p)",
    "",
    "    def rm_suffix(s: str, p: str) -> str:",
    "        return s.removesuffix(p)",
    "",
    "else:",
    "    def rm_prefix(s: str, p: str) -> str:",
    "        return s[len(p):] if s.startswith(p) else s",
    "",
    "    def rm_suffix(s: str, p: str) -> str:",
    "        return s[:-(len(p))] if s.endswith(p) else s",
    "",
    "",
    "UNMATCHED_TABLE_ROW = UnmatchedTableRow()",
]


def runtime_module_content(
    module: a.Module,
    *,
    http_strategy: HttpLibStrategy | None = None,
) -> str:
    """Return the full source text of the separate runtime module file.

    ``http_strategy`` is the HTTP library strategy (e.g. ``HttpxStrategy()``)
    chosen by the user. The runtime's ``ssc_rest_call`` references the
    transport exception class (e.g. ``httpx.HTTPError``) in its ``except``
    clause, so it must import the matching HTTP library. The strategy owns
    both the import line and the REST runtime source (Ok/Err/ssc_rest_call
    etc.) — single source of truth, no drift between parser and runtime.
    Defaults to ``HttpxStrategy`` when not provided.
    """
    strategy = http_strategy or HttpxStrategy()
    lines: list[str] = [
        "# autogenerated runtime helpers — do not edit",
        "from __future__ import annotations",
        "import re",
        "import sys",
        "from typing import Any, Callable, Dict, Generic, List, Literal, Mapping, Optional, TypeVar, Union",
        "from html import unescape as ssc_html_unescape",
    ]
    has_rest = module_has_rest(module)
    if has_rest:
        lines.extend(
            [
                "from dataclasses import dataclass, field",
                strategy.import_line,
            ]
        )
    lines.append("")
    lines.append("")
    lines.extend(_BASE_UTILITY_LINES)
    lines.append("")
    if has_rest:
        lines.extend(strategy.rest_runtime_lines())
    return "\n".join(lines)


def register_runtime_file(
    converter: Any,
    runtime_name: str = "sscgen_runtime",
    *,
    include_fallback: bool = False,
    http_strategy: HttpLibStrategy | None = None,
    transport_import_line: str | None = None,
) -> Callable[[list[a.Module]], str]:
    """Register a runtime module file provider on the converter.

    ``http_strategy`` is the canonical source for both the transport import
    line and the REST runtime source. It should match the HttpLibStrategy
    that will be applied to the parser codegen (see main.py).

    ``transport_import_line`` is a legacy fallback: when ``http_strategy``
    is not provided, the import line is taken from this argument and the
    REST runtime source defaults to ``HttpxStrategy``. Prefer passing
    ``http_strategy`` — single source of truth.
    """

    # Normalize legacy callers that pass only transport_import_line.
    if http_strategy is None:
        http_strategy = HttpxStrategy()

    def _apply_fallback(content: str) -> str:
        if not include_fallback:
            return content
        return content.replace(
            "_RE_HEX_ENTITY",
            'FALLBACK_HTML_STR = "<html><body></body></html>"\n\n_RE_HEX_ENTITY',
            1,
        )

    @converter.file(f"{runtime_name}.py")
    def _runtime_provider(module_ast: a.Module, meta):
        return _apply_fallback(
            runtime_module_content(
                module_ast,
                http_strategy=http_strategy,
            )
        )

    def _generate_runtime(modules: list[a.Module]) -> str:
        ref = next(
            (m for m in modules if module_has_rest(m)),
            modules[0],
        )
        return _apply_fallback(
            runtime_module_content(
                ref, http_strategy=http_strategy
            )
        )

    return _generate_runtime
