from __future__ import annotations

from ssc_codegen.targets.python.http_libs.base import HttpLibStrategy


class RequestsStrategy(HttpLibStrategy):
    """requests HTTP client strategy (sync-only, async via executor).

    ``requests`` has no async API - ``async_fetch`` wraps the sync call
    through ``asyncio.get_event_loop().run_in_executor()``.
    """

    import_line = "import requests"
    sync_client_type = "requests.Session"
    async_client_type = "requests.Session"
    transport_exception = "requests.RequestException"

    def rest_runtime_lines(self) -> list[str]:
        exc = self.transport_exception
        return [
            "_T = TypeVar('_T')",
            "_E = TypeVar('_E')",
            "",
            "@dataclass(frozen=True)",
            "class Ok(Generic[_T]):",
            "    status: int = 0",
            "    headers: Dict[str, str] = field(default_factory=dict)",
            "    value: _T = None  # type: ignore[assignment]",
            "    is_ok: Literal[True] = True",
            "",
            "@dataclass(frozen=True)",
            "class Err(Generic[_E]):",
            "    status: int = 0",
            "    headers: Dict[str, str] = field(default_factory=dict)",
            "    value: _E = None  # type: ignore[assignment]",
            "    is_ok: Literal[False] = False",
            "",
            "@dataclass(frozen=True)",
            "class UnknownErr(Err[Any]):",
            "    pass",
            "",
            "@dataclass(frozen=True)",
            "class TransportErr(Err[None]):",
            "    status: Literal[0] = 0",
            "    cause: str = ''",
            "    value: None = None",
            "    headers: Dict[str, str] = field(default_factory=dict)",
            "",
            "@dataclass(frozen=True)",
            "class ErrMatcher:",
            "    status: int",
            "    check: Optional[Callable[[dict], bool]] = None",
            "    factory: Optional[Callable[..., Err]] = None,",
            "",
            "    def match(",
            "        self,",
            "        status: int,",
            "        headers: Dict[str, str],",
            "        body: Any,",
            "    ) -> Optional[Err]:",
            "        if status != self.status:",
            "            return None",
            "        if self.check is not None:",
            "            if not isinstance(body, dict) or not self.check(body):",
            "                return None",
            "        return self.factory(headers=headers, value=body)",
            "",
            "",
            "def ssc_dispatch_err(",
            "    matchers: List[ErrMatcher],",
            "    status: int,",
            "    headers: Dict[str, str],",
            "    body: Any,",
            ") -> Optional[Err]:",
            "    for matcher in matchers:",
            "        err = matcher.match(status, headers, body)",
            "        if err is not None:",
            "            return err",
            "    if 200 <= status < 300:",
            "        return None",
            "    return UnknownErr(status=status, headers=headers, value=body)",
            "",
            "",
            "def ssc_rest_call(",
            "    client: requests.Session,",
            "    matchers: List[ErrMatcher],",
            "    method: str,",
            "    url: str,",
            "    value_fn: Optional[Callable[[Any], _T]] = None,",
            "    **kw: Any,",
            ") -> Union[Ok[_T], Err]:",
            "    try:",
            "        resp = client.request(method, url, **kw)",
            "        status = resp.status_code",
            "        headers = {k.lower(): v for k, v in resp.headers.items()}",
            "        try:",
            "            body = resp.json()",
            "        except Exception:",
            "            body = None",
            f"    except {exc} as exc:",
            "        return TransportErr(cause=repr(exc))",
            "    err = ssc_dispatch_err(matchers, status, headers, body)",
            "    if err is not None:",
            "        return err",
            "    value = body if value_fn is None else value_fn(body)",
            "    return Ok(status=status, headers=headers, value=value)",
            "",
            "",
            "async def ssc_rest_call_async(",
            "    client: requests.Session,",
            "    matchers: List[ErrMatcher],",
            "    method: str,",
            "    url: str,",
            "    value_fn: Optional[Callable[[Any], _T]] = None,",
            "    **kw: Any,",
            ") -> Union[Ok[_T], Err]:",
            "    import asyncio",
            "    loop = asyncio.get_event_loop()",
            "    return await loop.run_in_executor(",
            "        None,",
            "        lambda: ssc_rest_call(",
            "            client, matchers, method, url, value_fn, **kw",
            "        ),",
            "    )",
            "",
        ]
