from collections.abc import Callable

from ssc_codegen.converters.base import ConverterContext, BaseConverter

from ssc_codegen.ast import VariableType as VT
from ssc_codegen.ast.struct import PlaceholderSpec
import ssc_codegen.ast as a


from ssc_codegen.converters.helpers import (
    to_pascal_case,
    to_snake_case,
    jsonify_path_to_segments,
)
from ssc_codegen.converters.request_spec import (
    parse_to_spec,
    normalize_placeholder_names,
)
from ssc_codegen.converters.py_render import (
    render_value,
    render_dict,
    render_body,
    dict_needs_builder,
    emit_dict_builder,
)


# ---------------------------------------------------------------------------
# Shared constants and runtime templates (moved from py_helpers)
# ---------------------------------------------------------------------------

NOT_REQUIRED_IMPORT: list[str] = [
    "",
    "if sys.version_info >= (3, 11):",
    "    from typing import NotRequired",
    "else:",
    "    from typing_extensions import NotRequired",
]

_BASE_UTILITY_LINES: list[str] = [
    "_RE_HEX_ENTITY = re.compile(r'&#x([0-9a-fA-F]+);')",
    "_RE_UNICODE_ENTITY = re.compile(r'\\\\u([0-9a-fA-F]{4})')",
    "_RE_BYTES_ENTITY = re.compile(r'\\\\x([0-9a-fA-F]{2})')",
    "_RE_CHARS_MAP = {'\\b': '\\b', '\\f': '\\f', '\\n': '\\n', '\\r': '\\r', '\\t': '\\t'}",
    "",
    "def repl_map(s: str, rmap: Dict[str, str]) -> str:",
    "    for k, v in rmap.items():",
    "        s = s.replace(k, v)",
    "    return s",
    "",
    "def normalize_text(text: str) -> str:",
    "    return ' '.join(text.split()) if text else \"\"",
    "",
    "class _UnmatchedTableRow:",
    "    pass",
    "",
    "def unescape_text(text: str) -> str:",
    "    s = ssc_html_unescape(text)",
    "    s = _RE_HEX_ENTITY.sub(lambda m: chr(int(m.group(1), 16)), s)",
    "    s = _RE_UNICODE_ENTITY.sub(lambda m: chr(int(m.group(1), 16)), s)",
    "    s = _RE_BYTES_ENTITY.sub(lambda m: chr(int(m.group(1), 16)), s)",
    "    for ch, r in _RE_CHARS_MAP.items():",
    "        s = s.replace(ch, r)",
    "    return s",
    "",
    "if sys.version_info >= (3, 9):",
    "    def rm_prefix(s: str, p: str) -> str:",
    "        return s.removeprefix(p)",
    "",
    "    def rm_suffix(s: str, p: str) -> str:",
    "        return s.removesuffix(p)",
    "",
    "else:",
    "    def rm_prefix(s: str, p: str) -> str:",
    "        return s[len(p):] if s.startswith(p) else s",
    "",
    "    def rm_suffix(s: str, p: str) -> str:",
    "        return s[:-(len(p))] if s.endswith(p) else s",
    "",
    "",
    "UNMATCHED_TABLE_ROW = _UnmatchedTableRow()",
]

_BASE_EXPORT_NAMES: list[str] = [
    "repl_map",
    "normalize_text",
    "_UnmatchedTableRow",
    "unescape_text",
    "rm_prefix",
    "rm_suffix",
    "UNMATCHED_TABLE_ROW",
]


def base_utility_lines() -> list[str]:
    return [*_BASE_UTILITY_LINES, ""]


def runtime_export_names(node: a.Node) -> list[str]:
    names = list(_BASE_EXPORT_NAMES)
    if _module_has_rest(node):
        names.extend(
            ["Ok", "Err", "UnknownErr", "TransportErr", "ssc_parse_response"]
        )
    return names


def runtime_module_content(node: a.Node) -> str:
    lines: list[str] = [
        "# autogenerated runtime helpers — do not edit",
        "import re",
        "import sys",
        "from typing import Dict",
        "from html import unescape as ssc_html_unescape",
    ]
    has_rest = _module_has_rest(node)
    if has_rest:
        lines.extend(
            [
                "from dataclasses import dataclass, field",
                "from typing import Any, Generic, Literal, Mapping, TypeVar",
            ]
        )
    lines.append("")
    lines.append("")
    lines.extend(_BASE_UTILITY_LINES)
    lines.append("")
    if has_rest:
        lines.extend(rest_utilities(node))
    return "\n".join(lines)


def _module_has_rest(node: a.Node) -> bool:
    module: a.Node | None = node
    while module is not None and not isinstance(module, a.Module):
        module = getattr(module, "parent", None)
    if module is None:
        return False
    return any(isinstance(n, a.StructRest) for n in getattr(module, "body", []))


def module_is_rest_only(node: a.Node) -> bool:
    module: a.Node | None = node
    while module is not None and not isinstance(module, a.Module):
        module = getattr(module, "parent", None)
    if module is None:
        return False
    structs = [
        n for n in getattr(module, "body", []) if isinstance(n, a.StructBase)
    ]
    return len(structs) == 0 or all(
        isinstance(s, a.StructRest) for s in structs
    )


def rest_imports(node: a.Node) -> list[str]:
    if _module_has_rest(node):
        return [
            "from dataclasses import dataclass, field",
            "from typing import Generic, Literal, Mapping, TypeVar",
        ]
    return []


def http_client_import(ctx: ConverterContext) -> list[str]:
    client = ctx.meta.get("http_client", "")
    if client == "httpx":
        return ["import httpx"]
    return []


def rest_utilities(node: a.Node) -> list[str]:
    if not _module_has_rest(node):
        return []
    return [
        "_T = TypeVar('_T')",
        "_E = TypeVar('_E')",
        "\n",
        "@dataclass(frozen=True)",
        "class Ok(Generic[_T]):",
        "    status: int = 0",
        "    headers: Mapping[str, str] = field(default_factory=dict)",
        "    value: _T = None  # type: ignore[assignment]",
        "    is_ok: Literal[True] = True",
        "\n",
        "@dataclass(frozen=True)",
        "class Err(Generic[_E]):",
        "    status: int = 0",
        "    headers: Mapping[str, str] = field(default_factory=dict)",
        "    value: _E = None  # type: ignore[assignment]",
        "    is_ok: Literal[False] = False",
        "\n",
        "@dataclass(frozen=True)",
        "class UnknownErr(Err[Any]):",
        "    pass",
        "\n",
        "@dataclass(frozen=True)",
        "class TransportErr(Err[None]):",
        "    status: Literal[0] = 0",
        "    cause: str = ''",
        "    value: None = None",
        "    headers: Mapping[str, str] = field(default_factory=dict)",
        "\n\n",
        "def ssc_parse_response(_resp):",
        "    _status = _resp.status_code",
        "    _headers = {k.lower(): v for k, v in _resp.headers.items()}",
        "    try:",
        "        _body = _resp.json()",
        "    except Exception:",
        "        _body = None",
        "    return _status, _headers, _body",
        "\n\n",
    ]


PY_BASE_CONVERTER = BaseConverter()


PY_TYPES = {
    VT.STRING: "str",
    VT.BOOL: "bool",
    VT.INT: "int",
    VT.FLOAT: "float",
    VT.JSON: "{}Json",
    VT.NESTED: "{}Type",
    VT.OPT_FLOAT: "Optional[float]",
    VT.OPT_INT: "Optional[int]",
    VT.OPT_STRING: "Optional[str]",
    VT.LIST_INT: "List[int]",
    VT.LIST_STRING: "List[str]",
    VT.LIST_FLOAT: "List[float]",
    VT.LIST_DOCUMENT: "ResultSet[Tag]",
    VT.DOCUMENT: "Union[Tag, BeautifulSoup]",
    VT.NULL: "None",
}


@PY_BASE_CONVERTER(a.Docstring)
def pre_docstring(node: a.Docstring, _: ConverterContext):
    return [
        "# autogenerated by ssc-gen. DO NOT EDIT",
        f'''"""{node.value}"""''',
    ]


@PY_BASE_CONVERTER(a.Imports)
def pre_imports(node: a.Imports, ctx: ConverterContext):
    runtime = ctx.meta.get("runtime_module")
    if runtime:
        base_imports = [
            "import json",
            "import re",
            "import sys",
            "from dataclasses import dataclass",
            "from typing import TypedDict, Optional, Any, List, Dict, Union, Literal, Mapping",
        ]
        base_imports.extend(NOT_REQUIRED_IMPORT)
    else:
        base_imports = [
            "import json",
            "import re",
            "import sys",
            "from dataclasses import dataclass",
            "from typing import TypedDict, Optional, Any, List, Dict, Union, Literal, Mapping",
        ]
        if not module_is_rest_only(node):
            base_imports.append(
                "from html import unescape as ssc_html_unescape"
            )
        base_imports.extend(NOT_REQUIRED_IMPORT)
        base_imports.extend(rest_imports(node))

    # Get transform imports for Python (already collected during parsing)
    transform_imports = sorted(node.transform_imports.get("py", set()))

    return base_imports + transform_imports


# hook for add extra dependencies
@PY_BASE_CONVERTER.post(a.Imports)
def post_imports(node: a.Imports, ctx: ConverterContext):
    lines = []
    if not module_is_rest_only(node):
        lines.extend(
            [
                "from bs4 import BeautifulSoup, ResultSet, Tag",
                "BS4_FEATURES = 'lxml'",
            ]
        )
    lines.extend(http_client_import(ctx))
    return lines


@PY_BASE_CONVERTER(a.ImportsRest)
def pre_imports_rest(node: a.ImportsRest, ctx: ConverterContext):
    runtime = ctx.meta.get("runtime_module")
    if runtime or not _module_has_rest(node):
        return []
    return [
        "from dataclasses import dataclass, field",
        "from typing import Generic, Literal, Mapping, TypeVar",
    ]


@PY_BASE_CONVERTER(a.Utilities)
def pre_utilities(node: a.Utilities, ctx: ConverterContext):
    runtime = ctx.meta.get("runtime_module")
    if runtime:
        names = runtime_export_names(node)
        return [f"from .{runtime} import " + ", ".join(names), ""]

    if module_is_rest_only(node):
        lines = []
        lines.extend(rest_utilities(node))
        return lines

    lines = base_utility_lines()
    lines.extend(rest_utilities(node))
    return lines


@PY_BASE_CONVERTER(a.JsonDef, post_callback="})")
def pre_json_struct(node: a.JsonDef, _: ConverterContext):
    name = to_pascal_case(node.name)
    return [f'{name}Json = TypedDict("{name}Json", {{']


@PY_BASE_CONVERTER(a.JsonDefField)
def pre_json_field(node: a.JsonDefField, ctx: ConverterContext):
    if node.skip:
        return None
    name = node.alias or node.name
    type_ = PY_TYPES.get(node.ret, "Any")
    if node.ret == VT.JSON and node.ref_name:
        type_name = to_pascal_case(node.ref_name)
        type_ = type_.format(type_name)
        if node.is_array:
            type_ = f"List[{type_}]"
    if node.is_optional:
        type_ = f"Optional[{type_}]"
    if node.may_miss:
        type_ = f"NotRequired[{type_}]"
    return [f"{name!r}: {type_}, "]


@PY_BASE_CONVERTER(a.TypeDef)
def pre_typedef(node: a.TypeDef, _: ConverterContext):
    name = to_pascal_case(node.name)
    if node.struct_type == a.StructType.REST:
        # REST structs are API clients, not data types — no type alias
        return None
    if node.struct_type == a.StructType.DICT:
        return None
    elif node.struct_type == a.StructType.FLAT:
        return f"{name}Type = List[str]"
    return f"class {name}Type(TypedDict):"


@PY_BASE_CONVERTER(a.TypeDefField)
def pre_typedef_field(node: a.TypeDefField, ctx: ConverterContext):
    # alreay created type, skip
    if node.typedef.struct_type == a.StructType.FLAT:
        return
    name = to_snake_case(node.name)
    type_ = PY_TYPES.get(node.ret, "Any")
    if node.ret == VT.JSON and node.json_ref:
        type_name = to_pascal_case(node.json_ref)
        type_ = type_.format(type_name)
        if node.is_array:
            type_ = f"List[{type_}]"
    elif node.ret == VT.NESTED and node.nested_ref:
        type_name = to_pascal_case(node.nested_ref)
        type_ = type_.format(type_name)
        if node.is_array:
            type_ = f"List[{type_}]"
    if node.typedef.struct_type == a.StructType.DICT:
        if to_snake_case(node.name) == "value":
            typedef_name = to_pascal_case(node.typedef.name)
            return f"{typedef_name}Type = Dict[str, {type_}]"
        return None
    return [f"{ctx.indent}{name}: {type_}"]


# ---------------------------------------------------------------------------
# REST helpers — error dispatch, result aliases
# ---------------------------------------------------------------------------


def err_subclass_name(struct_name: str, err: a.ErrorResponse) -> str:
    base = f"{to_pascal_case(struct_name)}Err{err.status}"
    for key in err.required_keys:
        base += to_pascal_case(key.replace(".", "_").replace("-", "_"))
    if err.conditions:
        for key in err.conditions:
            base += to_pascal_case(key.replace(".", "_").replace("-", "_"))
    return base


def err_value_type(err: a.ErrorResponse, struct: a.StructBase) -> str:
    schema = err.schema_name
    if not schema:
        return "Any"
    type_name = f"{to_pascal_case(schema)}Json"
    module = struct.parent
    if module is not None:
        for n in module.body:
            if isinstance(n, a.JsonDef) and n.name == schema and n.is_array:
                return f"List[{type_name}]"
    return type_name


def _rest_err_union_type(struct: a.StructBase) -> str:
    variants: list[str] = []
    seen: set[str] = set()
    for err in struct.errors:
        cls_name = err_subclass_name(struct.name, err)
        if cls_name not in seen:
            seen.add(cls_name)
            variants.append(cls_name)
    return "Union[" + ", ".join([*variants, "UnknownErr", "None"]) + "]"


def _resolve_path_expr(body_var: str, path: str) -> str:
    parts = path.split(".")
    expr = body_var
    for seg in parts:
        if seg.isdigit():
            expr += f"[{seg}]"
        else:
            expr += f".get({seg!r})"
    return expr


def _condition_check_expr(err: a.ErrorResponse) -> str:
    parts: list[str] = []
    for key in err.required_keys:
        parts.append(f"{key!r} in _body")
    for path, value in err.conditions.items():
        lhs = _resolve_path_expr("_body", path)
        if isinstance(value, bool):
            parts.append(f"{lhs} == {value}")
        elif value is None:
            parts.append(f"{lhs} is None")
        elif isinstance(value, (int, float)):
            parts.append(f"{lhs} == {value}")
        else:
            parts.append(f"{lhs} == {value!r}")
    return " and ".join(parts)


def _emit_dispatch_err(node: a.StructBase, ctx: ConverterContext) -> list[str]:
    i1 = ctx.indent
    i2 = i1 + ctx.indent_char
    i3 = i2 + ctx.indent_char
    i4 = i3 + ctx.indent_char

    errors = node.errors
    status_errors = [
        e for e in errors if not e.conditions and not e.required_keys
    ]
    field_errors = [e for e in errors if e.conditions or e.required_keys]
    union_type = _rest_err_union_type(node)

    lines: list[str] = [
        f"{i1}@staticmethod",
        f"{i1}def ssc_dispatch_err("
        f"_status: int, _headers: Mapping[str, str], _body: Any"
        f") -> {union_type}:",
        f"{i2}if 200 <= _status < 300:",
    ]

    if field_errors:
        lines.append(f"{i3}if isinstance(_body, dict):")
        emitted_field_branch = False
        for err in field_errors:
            if 200 <= err.status < 300:
                cls_name = err_subclass_name(node.name, err)
                cond = _condition_check_expr(err)
                lines.append(f"{i4}if _status == {err.status} and {cond}:")
                lines.append(
                    f"{i4}{ctx.indent_char}return {cls_name}("
                    f"headers=_headers, value=_body)"
                )
                emitted_field_branch = True
        if not emitted_field_branch:
            lines.pop()
    lines.append(f"{i3}return None")

    for err in status_errors:
        cls_name = err_subclass_name(node.name, err)
        lines.append(f"{i2}if _status == {err.status}:")
        lines.append(f"{i3}return {cls_name}(headers=_headers, value=_body)")

    for err in field_errors:
        if not (200 <= err.status < 300):
            cls_name = err_subclass_name(node.name, err)
            cond = _condition_check_expr(err)
            lines.append(
                f"{i2}if _status == {err.status} "
                f"and isinstance(_body, dict) and {cond}:"
            )
            lines.append(
                f"{i3}return {cls_name}(headers=_headers, value=_body)"
            )

    lines.append(
        f"{i2}return UnknownErr(status=_status, headers=_headers, value=_body)"
    )
    return lines


def _result_alias_name(raw_name: str) -> str:
    return to_pascal_case(raw_name or "fetch") + "Result"


def _resolve_ok_payload_type(node: a.RequestConfig) -> str:
    if not node.response_schema:
        return "None"
    struct = node.parent
    module = struct.parent if struct is not None else None
    schema_type = f"{to_pascal_case(node.response_schema)}Json"
    if module is not None:
        for n in module.body:
            if isinstance(n, a.JsonDef) and n.name == node.response_schema:
                if n.is_array:
                    return f"List[{schema_type}]"
                break
    return schema_type


def _emit_result_aliases(struct: a.StructBase) -> list[str]:
    lines: list[str] = []
    for child in struct.body:
        if not isinstance(child, a.RequestConfig):
            continue
        raw_name = child.name or "fetch"
        alias_name = _result_alias_name(raw_name)
        payload = _resolve_ok_payload_type(child)
        err_variants: list[str] = []
        seen: set[str] = set()
        for err in struct.errors:
            cls_name = err_subclass_name(struct.name, err)
            if cls_name not in seen:
                seen.add(cls_name)
                err_variants.append(cls_name)
        parts = [f"Ok[{payload}]", *err_variants, "UnknownErr", "TransportErr"]
        lines.append(f"{alias_name} = Union[" + ", ".join(parts) + "]")
    return lines


# ---------------------------------------------------------------------------
# Struct handlers — one per struct type
# ---------------------------------------------------------------------------


@PY_BASE_CONVERTER(a.StructItem)
def pre_struct_item(node: a.StructItem, ctx: ConverterContext):
    return [f"class {to_pascal_case(node.name)}:"]


@PY_BASE_CONVERTER(a.StructList)
def pre_struct_list(node: a.StructList, ctx: ConverterContext):
    return [f"class {to_pascal_case(node.name)}:"]


@PY_BASE_CONVERTER(a.StructFlatList)
def pre_struct_flatlist(node: a.StructFlatList, ctx: ConverterContext):
    return [f"class {to_pascal_case(node.name)}:"]


@PY_BASE_CONVERTER(a.StructDict)
def pre_struct_dict(node: a.StructDict, ctx: ConverterContext):
    return [f"class {to_pascal_case(node.name)}:"]


@PY_BASE_CONVERTER(a.StructTable)
def pre_struct_table(node: a.StructTable, ctx: ConverterContext):
    return [f"class {to_pascal_case(node.name)}:"]


@PY_BASE_CONVERTER(a.StructRest)
def pre_struct_rest(node: a.StructRest, ctx: ConverterContext):
    name = to_pascal_case(node.name)
    lines: list[str] = []
    # Error subclasses (module-level, before class body)
    seen: set[str] = set()
    for err in node.errors:
        cls_name = err_subclass_name(node.name, err)
        if cls_name in seen:
            continue
        seen.add(cls_name)
        value_type = err_value_type(err, node)
        lines.append("@dataclass(frozen=True)")
        lines.append(f"class {cls_name}(Err[{value_type}]):")
        lines.append(f"    status: Literal[{err.status}] = {err.status}")
        lines.append("")
    # Result type aliases (module-level, before class body)
    alias_lines = _emit_result_aliases(node)
    if alias_lines:
        lines.extend(alias_lines)
        lines.append("")
    # Class header
    lines.append(f"class {name}:")
    # ssc_dispatch_err staticmethod (first member of class body, needs class-level indent)
    lines.extend(_emit_dispatch_err(node, ctx.deeper()))
    return lines


@PY_BASE_CONVERTER(a.StructDocstring)
def pre_struct_docstring(node: a.StructDocstring, ctx: ConverterContext):
    if node.value:
        lines = [f'{ctx.indent}"""']
        lines.extend(f"{ctx.indent}{line}" for line in node.value.splitlines())
        lines.append(f'{ctx.indent}"""')
        return lines
    return


# ---------------------------------------------------------------------------
# StartParse: return-type resolution + parse body generation
# ---------------------------------------------------------------------------

_PARSE_RETURN_TYPE = {
    a.StructItem: "{}Type",
    a.StructList: "List[{}Type]",
    a.StructFlatList: "List[str]",
    a.StructDict: "{}Type",
    a.StructTable: "{}Type",
}


@PY_BASE_CONVERTER(a.StartParse)
def pre_start_parse(node: a.StartParse, ctx: ConverterContext):
    name = to_pascal_case(node.struct.name)
    ret_type = _PARSE_RETURN_TYPE[type(node.struct)].format(name)
    return f"{ctx.indent}def parse(self) -> {ret_type}:"


def _emit_item_parse_body(
    node: a.StartParse, ctx: ConverterContext
) -> list[str]:
    i2, i3 = ctx.indent * 2, ctx.indent * 3
    lines = [f"{i2}return {{"]
    for field in node.fields:
        name = to_snake_case(field.name)
        lines.append(f"{i3}{name!r}: self._parse_{name}(self._doc),")
    lines.append(f"{i3} }}")
    return lines


def _emit_list_parse_body(
    node: a.StartParse, ctx: ConverterContext
) -> list[str]:
    i2, i3 = ctx.indent * 2, ctx.indent * 3
    lines = [f"{i2}return [{{"]
    for field in node.fields:
        name = to_snake_case(field.name)
        lines.append(f"{i3}{name!r}: self._parse_{name}(i),")
    lines.append(f"{i3}}} for i in self._split_doc(self._doc)]")
    return lines


def _emit_flatlist_parse_body(
    node: a.StartParse, ctx: ConverterContext
) -> list[str]:
    parent = node.struct
    i2 = ctx.indent * 2
    lines = [f"{i2}result: List[str] = []"]
    for field in node.fields:
        name = to_snake_case(field.name)
        if field.ret == VT.STRING:
            lines.append(f"{i2}result.append(self._parse_{name}(self._doc))")
        else:
            lines.append(f"{i2}result.extend(self._parse_{name}(self._doc))")
    if parent.keep_order:
        lines.append(f"{i2}return list(dict.fromkeys(result))")
    else:
        lines.append(f"{i2}return list(set(result))")
    return lines


def _emit_dict_parse_body(
    node: a.StartParse, ctx: ConverterContext
) -> list[str]:
    i2, i3 = ctx.indent * 2, ctx.indent * 3
    return [
        f"{i2}return {{",
        f"{i3} self._parse_key(i): self._parse_value(i)",
        f"{i3} for i in self._split_doc(self._doc)",
        f"{i3} }}",
    ]


def _emit_table_parse_body(
    node: a.StartParse, ctx: ConverterContext
) -> list[str]:
    parent = node.struct
    i2, i3, i4 = ctx.indent * 2, ctx.indent * 3, ctx.indent * 4
    name = to_pascal_case(parent.name)
    lines = [f"{i2}_result: {name}Type = {{}}"]
    lines.extend(
        [
            f"{i2}_table = self._table_config(self._doc)",
            f"{i2}for _row in self._parse_table_rows(_table):",
        ]
    )
    for f in node.fields:
        fname = to_snake_case(f.name)
        lines.append(f"{i3}_{fname} = self._parse_{fname}(_row)")
        lines.append(
            f"{i3}if _{fname} != UNMATCHED_TABLE_ROW and {fname!r} not in _result:"
        )
        lines.append(f"{i4}_result[{fname!r}] = _{fname}")
    lines.append(f"{i2}return _result")
    return lines


_EMIT_PARSE_BODY = {
    a.StructItem: _emit_item_parse_body,
    a.StructList: _emit_list_parse_body,
    a.StructFlatList: _emit_flatlist_parse_body,
    a.StructDict: _emit_dict_parse_body,
    a.StructTable: _emit_table_parse_body,
}


@PY_BASE_CONVERTER.post(a.StartParse)
def post_start_parse(node: a.StartParse, ctx: ConverterContext):
    lines: list[str] = []
    if node.use_pre_validate:
        lines.append(f"{ctx.indent * 2}self._pre_validate(self._doc)")
    lines.extend(_EMIT_PARSE_BODY[type(node.struct)](node, ctx))
    return lines


# required overload for target backend
@PY_BASE_CONVERTER(a.Init)
def pre_init(node: a.Init, ctx: ConverterContext):
    # REST structs have no document — no __init__
    if isinstance(node.parent, a.StructRest):
        return None
    init_node_names: list[str] = []
    for i in node.body:
        if isinstance(i, a.InitField):
            name = to_snake_case(i.name)
            init_node_names.append(name)
    code = [
        f"{ctx.indent}def __init__(self, document: Union[str, BeautifulSoup, Tag]):",
        f"{ctx.indent * 2}if isinstance(document, str):",
        f"{ctx.indent * 3}self._doc = BeautifulSoup(document, features=BS4_FEATURES)",
        f"{ctx.indent * 2}else:",
        f"{ctx.indent * 3}self._doc = document",
    ]
    for name in init_node_names:
        # late init vars
        code.append(
            f"{ctx.indent * 2}self._{name} = self._init_{name}(self._doc)"
        )
    return code


@PY_BASE_CONVERTER(a.InitField)
def pre_init_field(node: a.InitField, ctx: ConverterContext):
    name = to_snake_case(node.name)
    # cannot return nested or json, skip check
    ret_type = PY_TYPES.get(node.ret, "Any")
    return [
        f"    def _init_{name}(self, v: Union[Tag, BeautifulSoup]) -> {ret_type}:"
    ]


@PY_BASE_CONVERTER(a.Field)
def pre_struct_field(node: a.Field, ctx: ConverterContext):
    name = to_snake_case(node.name)
    ret_type = PY_TYPES.get(node.ret, "Any")
    # issue: how to detect if json arr or json struct simplier?
    if node.ret == VT.JSON:
        jsonify_node = [i for i in node.body if isinstance(i, a.Jsonify)][0]
        ret_type = ret_type.format(jsonify_node.schema_name)
        # Use is_array from jsonify_node (after path resolution), not from a.JsonDef schema
        if jsonify_node.is_array:
            ret_type = f"List[{ret_type}]"
    elif node.ret == VT.NESTED:
        nested_node = [i for i in node.body if isinstance(i, a.Nested)][0]
        ret_type = ret_type.format(nested_node.struct_name)
        if nested_node.is_array:
            ret_type = f"List[{ret_type}]"
    # table struct fields start with match { ... } and may return a sentinel
    if node.accept == VT.STRING:
        return [
            f"    def _parse_{name}(self, v: Union[Tag, BeautifulSoup]) -> Union[{ret_type}, _UnmatchedTableRow]:"
        ]
    return [
        f"    def _parse_{name}(self, v: Union[Tag, BeautifulSoup]) -> {ret_type}:"
    ]


@PY_BASE_CONVERTER(a.PreValidate)
def pre_struct_pre_validate(node: a.PreValidate, ctx: ConverterContext):
    # just validate, not modify document
    return [
        "    def _pre_validate(self, v: Union[Tag, BeautifulSoup]) -> None:"
    ]


@PY_BASE_CONVERTER(a.CheckMethod)
def pre_struct_check_method(node: a.CheckMethod, ctx: ConverterContext):
    from ssc_codegen.converters.helpers import to_snake_case

    method_name = to_snake_case(node.name)
    return [f"    def {method_name}(self) -> bool:"]


# @PY_BASE_CONVERTER.post(a.CheckMethod)
# def post_struct_check_method(node: a.CheckMethod, ctx: ConverterContext):
#     return [
#         "            return True",
#         "        except Exception:",
#         "            return False",
#     ]


@PY_BASE_CONVERTER(a.SplitDoc)
def pre_struct_split_doc(node: a.SplitDoc, ctx: ConverterContext):
    return [
        "    def _split_doc(self, v: Union[Tag, BeautifulSoup]) -> ResultSet[Tag]:",
    ]


@PY_BASE_CONVERTER(a.Key)
def pre_struct_key(node: a.Key, ctx: ConverterContext):
    # ret type always should be a string
    return ["    def _parse_key(self, v: Union[Tag, BeautifulSoup]) -> str:"]


@PY_BASE_CONVERTER(a.Value)
def pre_struct_value(node: a.Value, ctx: ConverterContext):
    ret_type = PY_TYPES.get(node.ret, "Any")
    # issue: how to detect if json arr or json struct simplier?
    if node.ret == VT.JSON:
        jsonify_node = [i for i in node.body if isinstance(i, a.Jsonify)][0]
        ret_type = ret_type.format(jsonify_node.schema_name)
        # Use is_array from jsonify_node (after path resolution), not from a.JsonDef schema
        if jsonify_node.is_array:
            ret_type = f"List[{ret_type}]"
    elif node.ret == VT.NESTED:
        nested_node = [i for i in node.body if isinstance(i, a.Nested)][0]
        ret_type = ret_type.format(nested_node.struct_name)
        if nested_node.is_array:
            ret_type = f"List[{ret_type}]"
    return [
        f"    def _parse_value(self, v: Union[Tag, BeautifulSoup]) -> {ret_type}:"
    ]


@PY_BASE_CONVERTER(a.TableConfig)
def pre_struct_table_config(node: a.TableConfig, ctx: ConverterContext):
    # should be a selector
    return [
        "    def _table_config(self,  v: Union[Tag, BeautifulSoup]) -> Tag:"
    ]


@PY_BASE_CONVERTER(a.TableMatchKey)
def pre_struct_table_match_key(node: a.TableMatchKey, ctx: ConverterContext):
    # should be returns a string
    return [
        "    def _table_match_key(self, v: Union[Tag, BeautifulSoup]) -> str:",
    ]


@PY_BASE_CONVERTER(a.TableRow)
def pre_struct_table_row(node: a.TableRow, ctx: ConverterContext):
    return [
        "    def _parse_table_rows(self, v: Union[Tag, BeautifulSoup]) -> ResultSet[Tag]:"
    ]


# EXPRESSIONS:


# SELECTORS
@PY_BASE_CONVERTER(a.CssSelect)
def pre_expr_css_select(node: a.CssSelect, ctx: ConverterContext):
    if node.queries:
        lines: list[str] = []
        for i, query in enumerate(node.queries):
            q = repr(query)
            if i == 0:
                lines.append(
                    f"{ctx.indent}{ctx.nxt} = {ctx.prv}.select_one({q})"
                )
            else:
                lines.append(f"{ctx.indent}if {ctx.nxt} is None:")
                lines.append(
                    f"{ctx.indent}    {ctx.nxt} = {ctx.prv}.select_one({q})"
                )
        return lines
    query = repr(node.query)
    return f"{ctx.indent}{ctx.nxt} = {ctx.prv}.select_one({query})"


@PY_BASE_CONVERTER(a.CssSelectAll)
def pre_expr_css_select_all(node: a.CssSelectAll, ctx: ConverterContext):
    if node.queries:
        lines: list[str] = []
        for i, query in enumerate(node.queries):
            q = repr(query)
            if i == 0:
                lines.append(f"{ctx.indent}{ctx.nxt} = {ctx.prv}.select({q})")
            else:
                lines.append(f"{ctx.indent}if not {ctx.nxt}:")
                lines.append(
                    f"{ctx.indent}    {ctx.nxt} = {ctx.prv}.select({q})"
                )
        return lines
    query = repr(node.query)
    return f"{ctx.indent}{ctx.nxt} = {ctx.prv}.select({query})"


@PY_BASE_CONVERTER(a.XpathSelect)
def pre_expr_xpath_select(node: a.XpathSelect, ctx: ConverterContext):
    raise NotImplementedError("BS4 not supports xpath queries")


@PY_BASE_CONVERTER(a.XpathSelectAll)
def pre_expr_xpath_select_all(node: a.XpathSelectAll, ctx: ConverterContext):
    raise NotImplementedError("BS4 not supports xpath queries")


@PY_BASE_CONVERTER(a.CssRemove)
def pre_expr_css_remove(node: a.CssRemove, ctx: ConverterContext):
    query = repr(node.query)
    # note: side effect call
    return [
        f"{ctx.indent}[i.decompose() for i in {ctx.prv}.select({query})]",
        f"{ctx.indent}{ctx.nxt} = {ctx.prv}",
    ]


@PY_BASE_CONVERTER(a.XpathRemove)
def pre_expr_xpath_remove(node: a.XpathRemove, ctx: ConverterContext):
    raise NotImplementedError("BS4 not supports xpath queries")


@PY_BASE_CONVERTER(a.Attr)
def pre_expr_attr(node: a.Attr, ctx: ConverterContext):
    keys = node.keys
    # bs4 return list of attrs if several values set in attr key, set string for API consistence
    # eg bs4 extract attrs workflow:
    # class="foo bar" -> ["foo", "bar"]
    if node.accept == VT.DOCUMENT:
        if len(keys) == 1:
            return f"{ctx.indent}{ctx.nxt} = ' '.join({ctx.prv}.get_attribute_list({keys[0]!r}))"
        return f"{ctx.indent}{ctx.nxt}=[' '.join({ctx.prv}.get_attribute_list(k)) for k in {keys} if {ctx.prv}.get(k)]"
    # LIST_DOCUMENT
    if len(keys) == 1:
        return f"{ctx.indent}{ctx.nxt} = [' '.join(e.get_attribute_list({keys[0]!r})) for e in {ctx.prv}]"
    return f"{ctx.indent}{ctx.nxt} = [' '.join(e.get_attribute_list(k)) for e in {ctx.prv} for k in {keys} if e.get(k)]"


@PY_BASE_CONVERTER(a.Text)
def pre_expr_text(node: a.Text, ctx: ConverterContext):
    if node.accept == VT.DOCUMENT:
        return f"{ctx.indent}{ctx.nxt} = {ctx.prv}.text"
    # LIST_DOCUMENT
    return f"{ctx.indent}{ctx.nxt} = [i.text for i in {ctx.prv}]"


@PY_BASE_CONVERTER(a.Raw)
def pre_expr_raw(node: a.Raw, ctx: ConverterContext):
    # in bs4 for extract raw html tag, need cast by str(TAG) expr
    if node.accept == VT.DOCUMENT:
        return f"{ctx.indent}{ctx.nxt} = str({ctx.prv})"
    # LIST_DOCUMENT
    return f"{ctx.indent}{ctx.nxt} = [str(i) for i in {ctx.prv}]"


# STRING
@PY_BASE_CONVERTER(a.Trim)
def pre_expr_trim(node: a.Trim, ctx: ConverterContext):
    if node.substr == "":
        value = ""
    else:
        value = repr(node.substr)
    if node.accept == VT.STRING:
        return [f"{ctx.indent}{ctx.nxt} = {ctx.prv}.strip({value})"]
    return [f"{ctx.indent}{ctx.nxt} = [i.strip({value}) for i in {ctx.prv}]"]


@PY_BASE_CONVERTER(a.Ltrim)
def pre_expr_ltrim(node: a.Ltrim, ctx: ConverterContext):
    if node.substr == "":
        value = ""
    else:
        value = repr(node.substr)
    if node.accept == VT.STRING:
        return [f"{ctx.indent}{ctx.nxt} = {ctx.prv}.lstrip({value})"]
    return [f"{ctx.indent}{ctx.nxt} = [i.lstrip({value}) for i in {ctx.prv}]"]


@PY_BASE_CONVERTER(a.Rtrim)
def pre_expr_rtrim(node: a.Rtrim, ctx: ConverterContext):
    if node.substr == "":
        value = ""
    else:
        value = repr(node.substr)
    if node.accept == VT.STRING:
        return [f"{ctx.indent}{ctx.nxt} = {ctx.prv}.rstrip({value})"]
    return [f"{ctx.indent}{ctx.nxt} = [i.rstrip({value}) for i in {ctx.prv}]"]


@PY_BASE_CONVERTER(a.RmPrefix)
def pre_expr_rm_prefix(node: a.RmPrefix, ctx: ConverterContext):
    value = repr(node.substr)
    # TODO: backport for Python < 3.10
    if node.accept == VT.STRING:
        return [f"{ctx.indent}{ctx.nxt} = rm_prefix({ctx.prv}, {value})"]
    return [
        f"{ctx.indent}{ctx.nxt} = [rm_prefix(i, {value}) for i in {ctx.prv}]"
    ]


@PY_BASE_CONVERTER(a.RmSuffix)
def pre_expr_rm_suffix(node: a.RmSuffix, ctx: ConverterContext):
    value = repr(node.substr)
    # TODO: backport for Python < 3.10
    if node.accept == VT.STRING:
        return [f"{ctx.indent}{ctx.nxt} = rm_suffix({ctx.prv}, {value})"]
    return [
        f"{ctx.indent}{ctx.nxt} = [rm_suffix(i, {value}) for i in {ctx.prv}]"
    ]


@PY_BASE_CONVERTER(a.RmPrefixSuffix)
def pre_expr_rm_prefix_suffix(node: a.RmPrefixSuffix, ctx: ConverterContext):
    prefix = repr(node.substr)
    suffix = repr(node.substr)
    # TODO: backport for Python < 3.10
    if node.accept == VT.STRING:
        return [
            f"{ctx.indent}{ctx.nxt} = rm_suffix(rm_prefix({ctx.prv}, {prefix}), {suffix})"
        ]
    return [
        f"{ctx.indent}{ctx.nxt} = [rm_suffix(rm_prefix(i, {prefix}), {suffix}) for i in {ctx.prv}]"
    ]


@PY_BASE_CONVERTER(a.Fmt)
def pre_expr_fmt(node: a.Fmt, ctx: ConverterContext):
    template = repr(node.template.replace("{{}}", "{}", 1))
    if node.accept == VT.STRING:
        return [f"{ctx.indent}{ctx.nxt} = {template}.format({ctx.prv})"]
    return [
        f"{ctx.indent}{ctx.nxt} = [{template}.format(i) for i in {ctx.prv}]"
    ]


@PY_BASE_CONVERTER(a.Repl)
def pre_expr_repl(node: a.Repl, ctx: ConverterContext):
    old = repr(node.old)
    new = repr(node.new)
    if node.accept == VT.STRING:
        return [f"{ctx.indent}{ctx.nxt} = {ctx.prv}.replace({old}, {new})"]
    return [
        f"{ctx.indent}{ctx.nxt} = [i.replace({old}, {new}) for i in {ctx.prv}]"
    ]


@PY_BASE_CONVERTER(a.ReplMap)
def pre_expr_repl_map(node: a.ReplMap, ctx: ConverterContext):
    repl_dict = repr(node.replacements)
    if node.accept == VT.STRING:
        return f"{ctx.indent}{ctx.nxt} = repl_map({ctx.prv}, {repl_dict})"
    return (
        f"{ctx.indent}{ctx.nxt} = [repl_map(i, {repl_dict}) for i in {ctx.prv}]"
    )


@PY_BASE_CONVERTER(a.Lower)
def pre_expr_lower(node: a.Lower, ctx: ConverterContext):
    if node.accept == VT.STRING:
        return f"{ctx.indent}{ctx.nxt} = {ctx.prv}.lower()"
    return f"{ctx.indent}{ctx.nxt} = [i.lower() for i in {ctx.prv}]"


@PY_BASE_CONVERTER(a.Upper)
def pre_expr_upper(node: a.Lower, ctx: ConverterContext):
    if node.accept == VT.STRING:
        return f"{ctx.indent}{ctx.nxt} = {ctx.prv}.upper()"
    return f"{ctx.indent}{ctx.nxt} = [i.upper() for i in {ctx.prv}]"


@PY_BASE_CONVERTER(a.Split)
def pre_expr_split(node: a.Split, ctx: ConverterContext):
    sep = repr(node.sep)
    # node.accept == VT.STRING:
    return f"{ctx.indent}{ctx.nxt} = {ctx.prv}.split({sep})"


@PY_BASE_CONVERTER(a.Join)
def pre_expr_join(node: a.Join, ctx: ConverterContext):
    sep = repr(node.sep)
    # node.accept == VT.LIST_STRING:
    return f"{ctx.indent}{ctx.nxt} = {sep}.join({ctx.prv})"


@PY_BASE_CONVERTER(a.NormalizeSpace)
def pre_expr_normalize(node: a.NormalizeSpace, ctx: ConverterContext):
    if node.accept == VT.STRING:
        return f"{ctx.indent}{ctx.nxt} = normalize_text({ctx.prv})"
    return f"{ctx.indent}{ctx.nxt} = [normalize_text(i) for i in {ctx.prv}]"


@PY_BASE_CONVERTER(a.Unescape)
def pre_expr_unescape(node: a.Unescape, ctx: ConverterContext):
    if node.accept == VT.STRING:
        return f"{ctx.indent}{ctx.nxt} = unescape_text({ctx.prv})"
    return f"{ctx.indent}{ctx.nxt} = [unescape_text(i) for i in {ctx.prv}]"


# REGEX


@PY_BASE_CONVERTER(a.Re)
def pre_expr_re(node: a.Re, ctx: ConverterContext):
    pattern = repr(node.pattern)
    if node.accept == VT.STRING:
        return f"{ctx.indent}{ctx.nxt} = re.search({pattern}, {ctx.prv})[1]"
    # LIST_STRING — map over items
    return f"{ctx.indent}{ctx.nxt} = [re.search({pattern}, i)[1] for i in {ctx.prv}]"


@PY_BASE_CONVERTER(a.ReAll)
def pre_expr_re_all(node: a.ReAll, ctx: ConverterContext):
    pattern = repr(node.pattern)
    return f"{ctx.indent}{ctx.nxt} = re.findall({pattern}, {ctx.prv})"


@PY_BASE_CONVERTER(a.ReSub)
def pre_expr_re_sub(node: a.ReSub, ctx: ConverterContext):
    pattern = repr(node.pattern)
    repl = repr(node.repl)
    if node.accept == VT.STRING:
        return f"{ctx.indent}{ctx.nxt} = re.sub({pattern}, {repl}, {ctx.prv})"
    return f"{ctx.indent}{ctx.nxt} = [re.sub({pattern}, {repl}, i) for i in {ctx.prv}]"


# array
@PY_BASE_CONVERTER(a.Index)
def pre_expr_index(node: a.Index, ctx: ConverterContext):
    idx = node.i
    return f"{ctx.indent}{ctx.nxt} = {ctx.prv}[{idx}]"


@PY_BASE_CONVERTER(a.Slice)
def pre_expr_slice(node: a.Slice, ctx: ConverterContext):
    start = node.start
    end = node.end
    return f"{ctx.indent}{ctx.nxt} = {ctx.prv}[{start}:{end}]"


@PY_BASE_CONVERTER(a.Len)
def pre_expr_len(node: a.Len, ctx: ConverterContext):
    return f"{ctx.indent}{ctx.nxt} = len({ctx.prv})"


@PY_BASE_CONVERTER(a.Unique)
def pre_expr_unique(node: a.Unique, ctx: ConverterContext):
    if node.keep_order:
        # py3.7+ dict preserves insertion order, so we can use it to remove duplicates while keeping order
        return f"{ctx.indent}{ctx.nxt} = list(dict.fromkeys({ctx.prv}))"
    return f"{ctx.indent}{ctx.nxt} = list(set({ctx.prv}))"


# casts
@PY_BASE_CONVERTER(a.ToInt)
def pre_expr_to_int(node: a.ToInt, ctx: ConverterContext):
    if node.accept == VT.STRING:
        return f"{ctx.indent}{ctx.nxt} = int({ctx.prv})"
    return f"{ctx.indent}{ctx.nxt} = [int(i) for i in {ctx.prv}]"


@PY_BASE_CONVERTER(a.ToFloat)
def pre_expr_to_float(node: a.ToFloat, ctx: ConverterContext):
    if node.accept == VT.STRING:
        return f"{ctx.indent}{ctx.nxt} = float({ctx.prv})"
    return f"{ctx.indent}{ctx.nxt} = [float(i) for i in {ctx.prv}]"


@PY_BASE_CONVERTER(a.ToBool)
def pre_expr_to_bool(node: a.ToBool, ctx: ConverterContext):
    # todo bool rule:
    return f"{ctx.indent}{ctx.nxt} = bool({ctx.prv})"


@PY_BASE_CONVERTER(a.Jsonify)
def pre_expr_jsonify(node: a.Jsonify, ctx: ConverterContext):
    # schema_name = to_pascal_case(node.schema_name) (used in type annotations, not in codegen)
    if node.path:
        path = ""
        parts = jsonify_path_to_segments(node.path)
        for part in parts:
            if part.isdigit():
                path += f"[{part}]"
            else:
                path += f"[{part}]"
        return f"{ctx.indent}{ctx.nxt} = json.loads({ctx.prv}){path}"
    return f"{ctx.indent}{ctx.nxt} = json.loads({ctx.prv})"


@PY_BASE_CONVERTER(a.Nested)
def pre_expr_nested(node: a.Nested, ctx: ConverterContext):
    struct_name = to_pascal_case(node.struct_name)
    return f"{ctx.indent}{ctx.nxt} = {struct_name}({ctx.prv}).parse()"


# controls
@PY_BASE_CONVERTER(a.Self)
def pre_expr_self(node: a.Self, ctx: ConverterContext):
    name = to_snake_case(node.name)
    # todo: standart pre calculated fields
    return f"{ctx.indent}{ctx.nxt} = self._{name}"


@PY_BASE_CONVERTER(a.TransformCall)
def pre_expr_transform_call(node: a.TransformCall, ctx: ConverterContext):
    # Find the Python implementation from transform_def
    if not node.transform_def:
        raise ValueError(f"TransformCall '{node.name}': transform_def is None")

    # Get Python-specific target
    py_target = None
    for target in node.transform_def.body:
        assert isinstance(target, a.TransformTarget)
        if target.lang == "py":
            py_target = target
            break

    if not py_target:
        raise ValueError(
            f"TransformCall '{node.name}': no 'py' implementation found"
        )

    # Generate code by substituting {{PRV}} and {{NXT}}
    lines = []
    for code_line in py_target.code:
        # Replace placeholders
        code_line = code_line.replace("{{PRV}}", ctx.prv)
        code_line = code_line.replace("{{NXT}}", ctx.nxt)
        lines.append(f"{ctx.indent}{code_line}")

    return lines


@PY_BASE_CONVERTER(a.Return)
def pre_expr_return(node: a.Return, ctx: ConverterContext):
    if isinstance(node.parent, a.PreValidate):
        return f"{ctx.indent}return"
    return f"{ctx.indent}return {ctx.prv}"


# TODO: recalc indents. Maybe required change node and fill a.Fallback body?
@PY_BASE_CONVERTER(a.FallbackStart)
def pre_expr_fallback_start(node: a.FallbackStart, ctx: ConverterContext):
    return f"{ctx.indent}try:"


@PY_BASE_CONVERTER(a.FallbackEnd)
def pre_expr_fallback_end(node: a.FallbackEnd, ctx: ConverterContext):
    return [
        f"{ctx.indent}except Exception:",
        f"{ctx.indent}{ctx.indent_char}return {node.value!r}",
    ]


# predicates
@PY_BASE_CONVERTER(
    a.Filter, post_callback=lambda _, ctx: ctx.deeper().indent + "]"
)
def pre_expr_filter(node: a.Filter, ctx: ConverterContext):
    # NXT = [i for i in PRV if ({CONDS...})]
    return f"{ctx.indent}{ctx.nxt} = [i for i in {ctx.prv} if "


# TODO: msg API
@PY_BASE_CONVERTER(
    a.Assert, post_callback=lambda _, ctx: ctx.deeper().indent + ")"
)
def pre_expr_assert(node: a.Assert, ctx: ConverterContext):
    return [
        f"{ctx.indent}i = {ctx.prv}",
        f"{ctx.indent}assert (",
    ]


@PY_BASE_CONVERTER.post(a.Assert)
def post_expr_assert(node: a.Assert, ctx: ConverterContext):
    return [ctx.deeper().indent + ")", f"{ctx.indent}{ctx.nxt} = {ctx.prv}"]


@PY_BASE_CONVERTER(a.Match)
def pre_expr_match(node: a.Match, ctx: ConverterContext):
    # _key = self._table_match_key(v)  — the row key to match against
    # predicates use `i` as the current item (the key string)
    # `i` alias lets all predicate handlers work unchanged inside match blocks
    return [
        f"{ctx.indent}i = self._table_match_key({ctx.prv})",
        f"{ctx.indent}if not (",
    ]


@PY_BASE_CONVERTER.post(a.Match)
def post_expr_match(node: a.Match, ctx: ConverterContext):
    # close the condition; if it doesn't match, return sentinel
    # if it matched, get the value cell via _parse_value and continue pipeline
    # ctx.indent = pipeline body level (e.g. depth=2 → 8 spaces)
    # deeper indent for the return statement inside the if-block
    return [
        f"{ctx.indent}):",
        f"{ctx.indent}{ctx.indent_char}return UNMATCHED_TABLE_ROW",
        f"{ctx.indent}{ctx.nxt} = self._parse_value({ctx.prv})",
    ]


@PY_BASE_CONVERTER(a.LogicAnd, post_callback=lambda _, ctx: ctx.indent + ")")
def pre_expr_logic_and(node: a.LogicAnd, ctx: ConverterContext):
    if ctx.index == 0:
        return f"{ctx.indent}("
    return f"{ctx.indent}and ("


@PY_BASE_CONVERTER(a.LogicOr, post_callback=lambda _, ctx: ctx.indent + ")")
def pre_expr_logic_or(node: a.LogicOr, ctx: ConverterContext):
    if ctx.index == 0:
        return f"{ctx.indent}("
    return f"{ctx.indent}or ("


@PY_BASE_CONVERTER(a.LogicNot, post_callback=lambda _, ctx: ctx.indent + ")")
def pre_expr_logic_not(node: a.LogicNot, ctx: ConverterContext):
    if ctx.index == 0:
        return f"{ctx.indent}not ("
    return f"{ctx.indent}and not ("


# note: all step-by-step conds acc by AND on
@PY_BASE_CONVERTER(a.PredCss)
def pre_expr_pred_css(node: a.PredCss, ctx: ConverterContext):
    query = repr(node.query)
    cond = f"i.select_one({query})"
    if ctx.index == 0:
        return ctx.indent + cond
    return ctx.indent + f"and {cond}"


@PY_BASE_CONVERTER(a.PredXpath)
def pre_expr_pred_xpath(node: a.PredXpath, ctx: ConverterContext):
    raise NotImplementedError("BS4 not supports XPATH queries")


@PY_BASE_CONVERTER(a.PredContains)
def pre_expr_pred_contains(node: a.PredContains, ctx: ConverterContext):
    values = node.values
    if len(values) == 1:
        cond = f"{values[0]!r} in i"
    else:
        cond = f"any(v in i for v in {values!r})"
    if ctx.index == 0:
        return ctx.indent + cond
    return ctx.indent + f"and {cond}"


@PY_BASE_CONVERTER(a.PredEq)
def pre_expr_pred_eq(node: a.PredEq, ctx: ConverterContext):
    values = node.values

    # should be single value (cmp by len)
    if isinstance(values[0], int):
        cond = f"len(i) == {values[0]}"
    elif len(values) == 1 and isinstance(values[0], str):
        cond = f"i == {values[0]!r}"
    # series of strings
    else:
        cond = f"any(i == v for v in {values!r})"

    if ctx.index == 0:
        return ctx.indent + cond
    return ctx.indent + f" and {cond}"


@PY_BASE_CONVERTER(a.PredNe)
def pre_expr_pred_ne(node: a.PredNe, ctx: ConverterContext):
    values = node.values

    # should be single value (cmp by len)
    if isinstance(values[0], int):
        cond = f"len(i) != {values[0]}"
    elif len(values) == 1 and isinstance(values[0], str):
        cond = f"i != {values[0]!r}"
    # series of strings
    else:
        # todo: change spec: for many args in ne - convert to all({COND...})
        cond = ctx.indent + f"all(i != v for v in {values!r})"
    if ctx.index == 0:
        return cond
    return ctx.indent + f"and {cond}"


@PY_BASE_CONVERTER(a.PredStarts)
def pre_expr_pred_starts(node: a.PredStarts, ctx: ConverterContext):
    values = node.values
    if len(values) == 1:
        cond = f"i.startswith({values[0]!r})"
    else:
        cond = f"any(i.startswith(v) for v in {values!r})"
    if ctx.index == 0:
        return ctx.indent + cond
    return ctx.indent + f"and {cond}"


@PY_BASE_CONVERTER(a.PredEnds)
def pre_expr_pred_ends(node: a.PredEnds, ctx: ConverterContext):
    values = node.values
    if len(values) == 1:
        cond = f"i.endswith({values[0]!r})"
    else:
        cond = f"any(i.endswith(v) for v in {values!r})"
    if ctx.index == 0:
        return ctx.indent + cond
    return ctx.indent + f"and {cond}"


# TODO: count expr simplify - reuse eq,gt,le with int argument
@PY_BASE_CONVERTER(a.PredCountEq)
def pre_expr_pred_count_eq(node: a.PredCountEq, ctx: ConverterContext):
    value = node.value
    cond = f"len(i) == {value}"
    if ctx.index == 0:
        return ctx.indent + cond
    return ctx.indent + f"and {cond}"


@PY_BASE_CONVERTER(a.PredCountGt)
def pre_expr_pred_count_gt(node: a.PredCountGt, ctx: ConverterContext):
    value = node.value
    cond = f"len(i) > {value}"
    if ctx.index == 0:
        return ctx.indent + cond
    return ctx.indent + f"and {cond}"


@PY_BASE_CONVERTER(a.PredCountLt)
def pre_expr_pred_count_lt(node: a.PredCountLt, ctx: ConverterContext):
    value = node.value
    cond = f"len(i) < {value}"
    if ctx.index == 0:
        return ctx.indent + cond
    return ctx.indent + f"and {cond}"


@PY_BASE_CONVERTER(a.PredCountNe)
def pre_expr_pred_count_ne(node: a.PredCountNe, ctx: ConverterContext):
    value = node.value
    cond = f"len(i) != {value}"
    if ctx.index == 0:
        return ctx.indent + cond
    return ctx.indent + f"and {cond}"


@PY_BASE_CONVERTER(a.PredCountGe)
def pre_expr_pred_count_ge(node: a.PredCountGe, ctx: ConverterContext):
    value = node.value
    cond = f"len(i) >= {value}"
    if ctx.index == 0:
        return ctx.indent + cond
    return ctx.indent + f"and {cond}"


@PY_BASE_CONVERTER(a.PredCountLe)
def pre_expr_pred_count_le(node: a.PredCountLe, ctx: ConverterContext):
    value = node.value
    cond = f"len(i) <= {value}"
    if ctx.index == 0:
        return ctx.indent + cond
    return ctx.indent + f"and {cond}"


@PY_BASE_CONVERTER(a.PredCountRange)
def pre_expr_pred_count_range(node: a.PredCountRange, ctx: ConverterContext):
    cond = f"{node.start} < len(i) < {node.end}"
    if ctx.index == 0:
        return ctx.indent + cond
    return ctx.indent + f"and {cond}"


@PY_BASE_CONVERTER(a.PredHasAttr)
def pre_expr_pred_has_attr(node: a.PredHasAttr, ctx: ConverterContext):
    keys = node.attrs
    if len(keys) == 1:
        cond = f"bool(i.get({keys[0]!r}, False))"
    else:
        cond = f"any(bool(i.get(k, False)) for k in {keys!r})"
    if ctx.index == 0:
        return ctx.indent + cond
    return ctx.indent + f"and {cond}"


@PY_BASE_CONVERTER(a.PredAttrContains)
def pre_expr_pred_attr_contains(
    node: a.PredAttrContains, ctx: ConverterContext
):
    name = node.name
    values = node.values
    # dont need check exists key
    if len(values) == 1:
        cond = f"{values[0]!r} in (' '.join(i.get_attribute_list({name!r})))"
    else:
        cond = f"any(v in (' '.join(i.get_attribute_list({name!r}))) for v in {values!r})"
    if ctx.index == 0:
        return ctx.indent + cond
    return ctx.indent + f"and {cond}"


@PY_BASE_CONVERTER(a.PredAttrEnds)
def pre_expr_pred_attr_ends(node: a.PredAttrEnds, ctx: ConverterContext):
    name = node.name
    values = node.values
    # dont need check exists key
    attr_value = f"(' '.join(i.get_attribute_list({name!r})))"
    if len(values) == 1:
        cond = f"{attr_value}.endswith({values[0]!r})"
    else:
        cond = f"{attr_value}.endswith({tuple(values)!r})"
    if ctx.index == 0:
        return ctx.indent + cond
    return ctx.indent + f"and {cond}"


@PY_BASE_CONVERTER(a.PredAttrEq)
def pre_expr_pred_attr_eq(node: a.PredAttrEq, ctx: ConverterContext):
    name = node.name
    values = node.values
    # dont need check exists key
    if len(values) == 1:
        cond = f"(' '.join(i.get_attribute_list({name!r}))) == {values[0]!r}"
    else:
        cond = f"any((' '.join(i.get_attribute_list({name!r}))) == v for v in {values!r})"
    if ctx.index == 0:
        return ctx.indent + cond
    return ctx.indent + f"and {cond}"


@PY_BASE_CONVERTER(a.PredAttrNe)
def pre_expr_pred_attr_ne(node: a.PredAttrNe, ctx: ConverterContext):
    name = node.name
    values = node.values
    # dont need check exists key
    attr_value = f"(' '.join(i.get_attribute_list({name!r})))"
    if len(values) == 1:
        cond = f"{attr_value} != {values[0]!r}"
    else:
        cond = f"all({attr_value} != v for v in {values!r})"
    if ctx.index == 0:
        return ctx.indent + cond
    return ctx.indent + f"and {cond}"


@PY_BASE_CONVERTER(a.PredAttrRe)
def pre_expr_pred_attr_re(node: a.PredAttrRe, ctx: ConverterContext):
    name = node.name
    pattern = repr(node.pattern)
    # dont need check exists key
    cond = f"bool(re.search({pattern}, (' '.join(i.get_attribute_list({name!r})))))"
    if ctx.index == 0:
        return ctx.indent + cond
    return ctx.indent + f"and {cond}"


@PY_BASE_CONVERTER(a.PredAttrStarts)
def pre_expr_pred_attr_starts(node: a.PredAttrStarts, ctx: ConverterContext):
    name = node.name
    values = node.values
    # dont need check exists key
    attr_value = f"(' '.join(i.get_attribute_list({name!r})))"
    if len(values) == 1:
        cond = f"{attr_value}.startswith({values[0]!r})"
    else:
        cond = f"{attr_value}.startswith({tuple(values)!r})"
    if ctx.index == 0:
        return ctx.indent + cond
    return ctx.indent + f"and {cond}"


@PY_BASE_CONVERTER(a.PredTextContains)
def pre_expr_pred_text_contains(
    node: a.PredTextContains, ctx: ConverterContext
):
    values = node.values
    if len(values) == 1:
        cond = f"{values[0]!r} in i.text"
    else:
        cond = f"any(v in i.text for v in {values!r})"
    if ctx.index == 0:
        return ctx.indent + cond
    return ctx.indent + f"and {cond}"


@PY_BASE_CONVERTER(a.PredTextEnds)
def pre_expr_pred_text_ends(node: a.PredTextEnds, ctx: ConverterContext):
    values = node.values
    if len(values) == 1:
        cond = f"i.text.endswith({values[0]!r})"
    else:
        cond = f"any(i.text.endswith(v) for v in {values!r})"
    if ctx.index == 0:
        return ctx.indent + cond
    return ctx.indent + f"and {cond}"


@PY_BASE_CONVERTER(a.PredTextRe)
def pre_expr_pred_text_re(node: a.PredTextRe, ctx: ConverterContext):
    pattern = repr(node.pattern)
    cond = f"bool(re.search({pattern}, i.text))"
    if ctx.index == 0:
        return ctx.indent + cond
    return ctx.indent + f"and {cond}"


@PY_BASE_CONVERTER(a.PredTextStarts)
def pre_expr_pred_text_starts(node: a.PredTextStarts, ctx: ConverterContext):
    values = node.values
    if len(values) == 1:
        cond = f"i.text.startswith({values[0]!r})"
    else:
        cond = f"any(i.text.startswith(v) for v in {values!r})"
    if ctx.index == 0:
        return ctx.indent + cond
    return ctx.indent + f"and {cond}"


@PY_BASE_CONVERTER(a.PredIn)
def pre_expr_pred_in(node: a.PredIn, ctx: ConverterContext):
    values = node.values
    if len(values) == 1:
        cond = f"{values[0]!r} in i"
    else:
        cond = f"any(v in i for v in {values!r})"
    if ctx.index == 0:
        return ctx.indent + cond
    return ctx.indent + f"and {cond}"


@PY_BASE_CONVERTER(a.PredGe)
def pre_expr_pred_ge(node: a.PredGe, ctx: ConverterContext):
    value = node.value
    cond = f"len(i) >= {value}"
    if ctx.index == 0:
        return ctx.indent + cond
    return ctx.indent + f"and {cond}"


@PY_BASE_CONVERTER(a.PredGt)
def pre_expr_pred_gt(node: a.PredGt, ctx: ConverterContext):
    value = node.value
    cond = f"len(i) > {value}"
    if ctx.index == 0:
        return ctx.indent + cond
    return ctx.indent + f"and {cond}"


@PY_BASE_CONVERTER(a.PredLe)
def pre_expr_pred_le(node: a.PredLe, ctx: ConverterContext):
    value = node.value
    cond = f"len(i) <= {value}"
    if ctx.index == 0:
        return ctx.indent + cond
    return ctx.indent + f"and {cond}"


@PY_BASE_CONVERTER(a.PredLt)
def pre_expr_pred_lt(node: a.PredLt, ctx: ConverterContext):
    value = node.value
    cond = f"len(i) < {value}"
    if ctx.index == 0:
        return ctx.indent + cond
    return ctx.indent + f"and {cond}"


@PY_BASE_CONVERTER(a.PredRange)
def pre_expr_pred_range(node: a.PredRange, ctx: ConverterContext):
    start = node.start
    end = node.end
    cond = f"{start} < len(i) < {end}"
    if ctx.index == 0:
        return ctx.indent + cond
    return ctx.indent + f"and {cond}"


@PY_BASE_CONVERTER(a.PredRe)
def pre_expr_pred_re(node: a.PredRe, ctx: ConverterContext):
    pattern = repr(node.pattern)
    cond = f"bool(re.search({pattern}, i))"
    if ctx.index == 0:
        return ctx.indent + cond
    return ctx.indent + f"and {cond}"


@PY_BASE_CONVERTER(a.PredReAll)
def pre_expr_pred_re_all(node: a.PredReAll, ctx: ConverterContext):
    # assert specific expr
    pattern = repr(node.pattern)
    cond = f"all(re.search({pattern}, j) for j in i)"
    if ctx.index == 0:
        return ctx.indent + cond
    return ctx.indent + f"and {cond}"


@PY_BASE_CONVERTER(a.PredReAny)
def pre_expr_pred_re_any(node: a.PredReAny, ctx: ConverterContext):
    # assert specific expr
    pattern = repr(node.pattern)
    cond = f"any(re.search({pattern}, j) for j in i)"
    if ctx.index == 0:
        return ctx.indent + cond
    return ctx.indent + f"and {cond}"


# ---------------------------------------------------------------------------
# RequestConfig: spec building + REST/non-REST method generation
# ---------------------------------------------------------------------------


_PH_PRIM_ANNO: dict[str, str] = {
    "str": "str",
    "int": "int",
    "float": "float",
    "bool": "bool",
}


def _ph_to_py_annotation(ph: PlaceholderSpec) -> tuple[str, str]:
    anno = _PH_PRIM_ANNO[ph.type_name]
    if ph.is_array:
        anno = f"List[{anno}]"
    if ph.is_optional:
        return f"Optional[{anno}]", " = None"
    return anno, ""


def _render_signature_params(placeholders: list[PlaceholderSpec]) -> str:
    if not placeholders:
        return ""
    required = [p for p in placeholders if not p.is_optional]
    optional = [p for p in placeholders if p.is_optional]
    parts: list[str] = []
    for ph in required + optional:
        anno, default = _ph_to_py_annotation(ph)
        parts.append(f"{ph.name}: {anno}{default}")
    return ", *, " + ", ".join(parts)


def _build_request_parts(node: a.RequestConfig, ctx: ConverterContext):
    """Parse raw HTTP payload and build all request components."""
    spec = normalize_placeholder_names(
        parse_to_spec(node.raw_payload), to_snake_case
    )
    ind = ctx.indent_char
    i1 = ctx.indent
    i2 = i1 + ind
    i3 = i2 + ind
    i4 = i3 + ind

    ph_params = _render_signature_params(spec.placeholders)
    pre_lines: list[str] = []
    call_args: list[str] = [f"{spec.method!r},", f"{render_value(spec.url)},"]

    def _dict_arg(kwarg: str, d: dict[str, str], varname: str) -> None:
        if not d:
            return
        if dict_needs_builder(d):
            pre_lines.extend(emit_dict_builder(varname, d, i2))
            call_args.append(f"{kwarg}={varname},")
        else:
            call_args.append(f"{kwarg}={render_dict(d)},")

    _dict_arg("headers", spec.headers, "_headers")
    _dict_arg("cookies", spec.cookies, "_cookies")
    _dict_arg("params", spec.params, "_params")
    body_result = render_body(spec)
    if body_result:
        kwarg_name, body_expr = body_result
        call_args.append(f"{kwarg_name}={body_expr},")

    return spec, call_args, pre_lines, ph_params, i1, i2, i3, i4


def _emit_rest_methods(
    node: a.RequestConfig,
    call_args: list[str],
    pre_lines: list[str],
    ph_params: str,
    i1: str,
    i2: str,
    i3: str,
    i4: str,
) -> list[str]:
    method_name = to_snake_case(node.name) if node.name else "fetch"
    ret_type = _result_alias_name(node.name)
    ok_value = "_body" if node.response_schema else "None"
    lines: list[str] = []
    for is_async, mname, ctype in [
        (False, method_name, "httpx.Client"),
        (True, f"async_{method_name}", "httpx.AsyncClient"),
    ]:
        akw = "async " if is_async else ""
        awk = "await " if is_async else ""
        lines.append(f"{i1}@classmethod")
        lines.append(
            f"{i1}{akw}def {mname}(cls, client: {ctype}{ph_params}) -> {ret_type}:"
        )
        if node.doc:
            lines.append(f'{i2}"""{node.doc}"""')
        lines.extend(pre_lines)
        lines.append(f"{i2}try:")
        lines.append(f"{i3}_resp = {awk}client.request(")
        lines.extend(f"{i4}{a}" for a in call_args)
        lines.append(f"{i3})")
        lines.append(f"{i2}except httpx.HTTPError as _exc:")
        lines.append(f"{i3}return TransportErr(cause=repr(_exc))")
        lines.append(
            f"{i2}_status, _headers, _body = ssc_parse_response(_resp)"
        )
        lines.append(
            f"{i2}_err = cls.ssc_dispatch_err(_status, _headers, _body)"
        )
        lines.append(f"{i2}if _err is not None:")
        lines.append(f"{i3}return _err")
        lines.append(
            f"{i2}return Ok(status=_status, headers=_headers, value={ok_value})"
        )
        lines.append("")
    lines.pop()
    return lines


def _emit_fetch_methods(
    node: a.RequestConfig,
    call_args: list[str],
    pre_lines: list[str],
    ph_params: str,
    i1: str,
    i2: str,
    i3: str,
) -> list[str]:
    struct_name = to_pascal_case(node.parent.name)  # type: ignore[union-attr]
    suffix = ("_" + to_snake_case(node.name)) if node.name else ""
    response_path = node.response_path
    response_join = node.response_join
    lines: list[str] = []
    for is_async, mname, ctype in [
        (False, f"fetch{suffix}", "httpx.Client"),
        (True, f"async_fetch{suffix}", "httpx.AsyncClient"),
    ]:
        akw = "async " if is_async else ""
        awk = "await " if is_async else ""
        lines.append(f"{i1}@classmethod")
        lines.append(
            f'{i1}{akw}def {mname}(cls, client: {ctype}{ph_params}) -> "{struct_name}":'
        )
        lines.extend(pre_lines)
        lines.append(f"{i2}_resp = {awk}client.request(")
        lines.extend(f"{i3}{a}" for a in call_args)
        lines.append(f"{i2})")
        lines.append(f"{i2}_resp.raise_for_status()")
        if response_path:
            accessor = "".join(f"[{p!r}]" for p in response_path.split("."))
            lines.append(f"{i2}_data = _resp.json()")
            if response_join:
                lines.append(
                    f"{i2}_body = {response_join!r}.join(_data{accessor})"
                )
            else:
                lines.append(f"{i2}_body = _data{accessor}")
        else:
            lines.append(f"{i2}_body = _resp.text")
        lines.append(f"{i2}return cls(_body)")
        lines.append("")
    lines.pop()
    return lines


@PY_BASE_CONVERTER(a.RequestConfig)
def pre_request_config(node: a.RequestConfig, ctx: ConverterContext):
    _, call_args, pre_lines, ph_params, i1, i2, i3, i4 = _build_request_parts(
        node, ctx
    )
    if isinstance(node.parent, a.StructRest):
        return _emit_rest_methods(
            node, call_args, pre_lines, ph_params, i1, i2, i3, i4
        )
    return _emit_fetch_methods(
        node, call_args, pre_lines, ph_params, i1, i2, i3
    )


@PY_BASE_CONVERTER(a.ErrorResponse)
def pre_error_response(node: a.ErrorResponse, _: ConverterContext):
    # error spec consumed by pre_request_config; no direct emission
    return None


def register_runtime_file(
    converter: BaseConverter,
    runtime_name: str = "sscgen_runtime",
    *,
    include_fallback: bool = False,
) -> Callable[[list[a.Node]], str]:
    """Register a runtime module file provider on the converter.

    Returns a callable ``generate_runtime(modules) -> str`` that produces
    the runtime file content for a list of parsed modules, picking the one
    with REST structs as the reference AST automatically.
    """

    def _apply_fallback(content: str) -> str:
        if not include_fallback:
            return content
        return content.replace(
            "_RE_HEX_ENTITY",
            'FALLBACK_HTML_STR = "<html><body></body></html>"\n\n_RE_HEX_ENTITY',
            1,
        )

    @converter.file(f"{runtime_name}.py")
    def _runtime_provider(module_ast, meta):
        return _apply_fallback(runtime_module_content(module_ast))

    def _generate_runtime(modules: list[a.Node]) -> str:
        ref = next(
            (m for m in modules if _module_has_rest(m)),
            modules[0],
        )
        return _apply_fallback(runtime_module_content(ref))

    return _generate_runtime
