"""Python code-generation helpers for REST runtime, error dispatch, and fetch methods.

Consumed by the Python converter family (py_bs4, py_lxml, py_parsel, py_slax).
Value/dict/body rendering helpers live in ``py_render``.
"""

from __future__ import annotations

import ssc_codegen.ast as a
from ssc_codegen.ast.struct import PlaceholderSpec

from ssc_codegen.converters.base import ConverterContext

from ssc_codegen.converters.helpers import to_pascal_case

NOT_REQUIRED_IMPORT: list[str] = [
    "",
    "if sys.version_info >= (3, 11):",
    "    from typing import NotRequired",
    "else:",
    "    from typing_extensions import NotRequired",
]

__all__ = [
    # Shared import fragments
    "NOT_REQUIRED_IMPORT",
    # Runtime module generation
    "base_utility_lines",
    "runtime_export_names",
    "runtime_module_content",
    # Module introspection
    "module_is_rest_only",
    "rest_imports",
    "http_client_import",
    "rest_utilities",
    # REST error dispatch
    "err_subclass_name",
    "err_value_type",
    "emit_dispatch_err_py",
    # Method builders
    "render_signature_params",
    "emit_result_aliases",
    "resolve_response_type",
    "build_request_method",
    "build_rest_method",
]


# ---------------------------------------------------------------------------
# Runtime module helpers (lines emitted into generated code)
# ---------------------------------------------------------------------------

_BASE_UTILITY_LINES: list[str] = [
    "_RE_HEX_ENTITY = re.compile(r'&#x([0-9a-fA-F]+);')",
    "_RE_UNICODE_ENTITY = re.compile(r'\\\\u([0-9a-fA-F]{4})')",
    "_RE_BYTES_ENTITY = re.compile(r'\\\\x([0-9a-fA-F]{2})')",
    "_RE_CHARS_MAP = {'\\b': '\\b', '\\f': '\\f', '\\n': '\\n', '\\r': '\\r', '\\t': '\\t'}",
    "",
    "def repl_map(s: str, rmap: Dict[str, str]) -> str:",
    "    for k, v in rmap.items():",
    "        s = s.replace(k, v)",
    "    return s",
    "",
    "def normalize_text(text: str) -> str:",
    "    return ' '.join(text.split()) if text else \"\"",
    "",
    "class _UnmatchedTableRow:",
    "    pass",
    "",
    "def unescape_text(text: str) -> str:",
    "    s = _html_unescape(text)",
    "    s = _RE_HEX_ENTITY.sub(lambda m: chr(int(m.group(1), 16)), s)",
    "    s = _RE_UNICODE_ENTITY.sub(lambda m: chr(int(m.group(1), 16)), s)",
    "    s = _RE_BYTES_ENTITY.sub(lambda m: chr(int(m.group(1), 16)), s)",
    "    for ch, r in _RE_CHARS_MAP.items():",
    "        s = s.replace(ch, r)",
    "    return s",
    "",
    "if sys.version_info >= (3, 9):",
    "    def rm_prefix(s: str, p: str) -> str:",
    "        return s.removeprefix(p)",
    "",
    "    def rm_suffix(s: str, p: str) -> str:",
    "        return s.removesuffix(p)",
    "",
    "else:",
    "    def rm_prefix(s: str, p: str) -> str:",
    "        return s[len(p):] if s.startswith(p) else s",
    "",
    "    def rm_suffix(s: str, p: str) -> str:",
    "        return s[:-(len(p))] if s.endswith(p) else s",
    "",
    "",
    "UNMATCHED_TABLE_ROW = _UnmatchedTableRow()",
]

_BASE_EXPORT_NAMES: list[str] = [
    "repl_map",
    "normalize_text",
    "_UnmatchedTableRow",
    "unescape_text",
    "rm_prefix",
    "rm_suffix",
    "UNMATCHED_TABLE_ROW",
]


def base_utility_lines(*, include_fallback_html: bool = False) -> list[str]:
    """Return the standard utility helper lines for generated code.

    Single source of truth replacing inline copies in py_bs4 / py_lxml.
    """
    lines: list[str] = []
    if include_fallback_html:
        lines.append('FALLBACK_HTML_STR = "<html><body></body></html>"')
        lines.append("")
    lines.extend(_BASE_UTILITY_LINES)
    lines.append("")
    return lines


def runtime_export_names(
    node: a.Node, include_fallback_html: bool = False
) -> list[str]:
    """Names the main module must import from the runtime module."""
    names = list(_BASE_EXPORT_NAMES)
    if include_fallback_html:
        names.append("FALLBACK_HTML_STR")
    if _module_has_rest(node):
        names.extend(
            ["Ok", "Err", "UnknownErr", "TransportErr", "_parse_response"]
        )
    return names


def runtime_module_content(
    node: a.Node, include_fallback_html: bool = False
) -> str:
    """Full content of the runtime module as a string."""
    lines: list[str] = [
        "# autogenerated runtime helpers — do not edit",
        "import re",
        "import sys",
        "from typing import Dict",
        "from html import unescape as _html_unescape",
    ]
    has_rest = _module_has_rest(node)
    if has_rest:
        lines.extend(
            [
                "from dataclasses import dataclass, field",
                "from typing import Any, Generic, Literal, Mapping, TypeVar",
            ]
        )
    lines.append("")
    lines.append("")
    if include_fallback_html:
        lines.append('FALLBACK_HTML_STR = "<html><body></body></html>"')
        lines.append("")
    lines.extend(_BASE_UTILITY_LINES)
    lines.append("")
    if has_rest:
        lines.extend(rest_utilities(node))
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Module introspection
# ---------------------------------------------------------------------------


def _module_has_rest(node: a.Node) -> bool:
    """True if the node's enclosing Module has any ``struct type=rest``."""
    module: a.Node | None = node
    while module is not None and not isinstance(module, a.Module):
        module = getattr(module, "parent", None)
    if module is None:
        return False
    return any(
        isinstance(n, a.Struct) and n.is_rest
        for n in getattr(module, "body", [])
    )


def module_is_rest_only(node: a.Node) -> bool:
    """True if the module has no HTML-parsing structs (all rest or empty)."""
    module: a.Node | None = node
    while module is not None and not isinstance(module, a.Module):
        module = getattr(module, "parent", None)
    if module is None:
        return False
    structs = [
        n for n in getattr(module, "body", []) if isinstance(n, a.Struct)
    ]
    return len(structs) == 0 or all(s.is_rest for s in structs)


def rest_imports(node: a.Node) -> list[str]:
    """Extra imports required when the module has any ``struct type=rest``."""
    if not _module_has_rest(node):
        return []
    return [
        "from dataclasses import dataclass, field",
        "from typing import Generic, Literal, Mapping, TypeVar",
    ]


def http_client_import(ctx: ConverterContext) -> list[str]:
    """Return the import line(s) for the chosen HTTP client, or ``[]``."""
    client = ctx.meta.get("http_client", "")
    if client == "requests":
        return ["import requests"]
    if client == "httpx":
        return ["import httpx"]
    return []


def rest_utilities(node: a.Node) -> list[str]:
    """Ok/Err/UnknownErr/TransportErr + _parse_response block; empty if no REST."""
    if not _module_has_rest(node):
        return []
    return [
        "_T = TypeVar('_T')",
        "_E = TypeVar('_E')",
        "\n",
        "@dataclass(frozen=True)",
        "class Ok(Generic[_T]):",
        "    status: int = 0",
        "    headers: Mapping[str, str] = field(default_factory=dict)",
        "    value: _T = None  # type: ignore[assignment]",
        "    is_ok: Literal[True] = True",
        "\n",
        "@dataclass(frozen=True)",
        "class Err(Generic[_E]):",
        "    status: int = 0",
        "    headers: Mapping[str, str] = field(default_factory=dict)",
        "    value: _E = None  # type: ignore[assignment]",
        "    is_ok: Literal[False] = False",
        "\n",
        "@dataclass(frozen=True)",
        "class UnknownErr(Err[Any]):",
        "    pass",
        "\n",
        "@dataclass(frozen=True)",
        "class TransportErr(Err[None]):",
        "    status: Literal[0] = 0",
        "    cause: str = ''",
        "    value: None = None",
        "    headers: Mapping[str, str] = field(default_factory=dict)",
        "\n\n",
        "def _parse_response(_resp):",
        "    _status = _resp.status_code",
        "    _headers = {k.lower(): v for k, v in _resp.headers.items()}",
        "    try:",
        "        _body = _resp.json()",
        "    except Exception:",
        "        _body = None",
        "    return _status, _headers, _body",
        "\n\n",
    ]


# ---------------------------------------------------------------------------
# REST error dispatch
# ---------------------------------------------------------------------------


def err_subclass_name(struct_name: str, err: a.ErrorResponse) -> str:
    """Naming: ``<Struct>Err<Status>[<ConditionKeys>]``."""
    base = f"{to_pascal_case(struct_name)}Err{err.status}"
    for key in err.required_keys:
        base += to_pascal_case(key.replace(".", "_").replace("-", "_"))
    if err.conditions:
        for key in err.conditions:
            base += to_pascal_case(key.replace(".", "_").replace("-", "_"))
    return base


def err_value_type(err: a.ErrorResponse, struct: a.Struct) -> str:
    """Return the typed value annotation for an Err subclass."""
    schema = err.schema_name
    if not schema:
        return "Any"
    type_name = f"{to_pascal_case(schema)}Json"
    module = struct.parent
    if module is not None:
        for n in module.body:
            if isinstance(n, a.JsonDef) and n.name == schema and n.is_array:
                return f"List[{type_name}]"
    return type_name


def _rest_err_union_type(struct: a.Struct) -> str:
    """Return the typed union of all Err variants for _dispatch_err sig."""
    variants: list[str] = []
    seen: set[str] = set()
    for err in struct.errors:
        cls_name = err_subclass_name(struct.name, err)
        if cls_name not in seen:
            seen.add(cls_name)
            variants.append(cls_name)
    return "Union[" + ", ".join([*variants, "UnknownErr", "None"]) + "]"


def _resolve_path_expr(body_var: str, path: str) -> str:
    """Generate a Python expression navigating a dot-path into a JSON body."""
    parts = path.split(".")
    expr = body_var
    for seg in parts:
        if seg.isdigit():
            expr += f"[{seg}]"
        else:
            expr += f".get({seg!r})"
    return expr


def _condition_check_expr(err: a.ErrorResponse) -> str:
    """Build a compound condition expression for an @error's field conditions."""
    parts: list[str] = []
    for key in err.required_keys:
        parts.append(f"{key!r} in _body")
    for path, value in err.conditions.items():
        lhs = _resolve_path_expr("_body", path)
        if isinstance(value, bool):
            parts.append(f"{lhs} == {value}")
        elif value is None:
            parts.append(f"{lhs} is None")
        elif isinstance(value, (int, float)):
            parts.append(f"{lhs} == {value}")
        else:
            parts.append(f"{lhs} == {value!r}")
    return " and ".join(parts)


def emit_dispatch_err_py(node: a.Struct, ctx: ConverterContext) -> list[str]:
    """Emit the ``_dispatch_err`` @staticmethod lines inside a REST class."""
    i1 = ctx.indent
    i2 = i1 + ctx.indent_char
    i3 = i2 + ctx.indent_char
    i4 = i3 + ctx.indent_char

    errors = node.errors
    status_errors = [
        e for e in errors if not e.conditions and not e.required_keys
    ]
    field_errors = [e for e in errors if e.conditions or e.required_keys]
    union_type = _rest_err_union_type(node)

    lines: list[str] = [
        f"{i1}@staticmethod",
        f"{i1}def _dispatch_err("
        f"_status: int, _headers: Mapping[str, str], _body: Any"
        f") -> {union_type}:",
        f"{i2}if 200 <= _status < 300:",
    ]

    if field_errors:
        lines.append(f"{i3}if isinstance(_body, dict):")
        emitted_field_branch = False
        for err in field_errors:
            if 200 <= err.status < 300:
                cls_name = err_subclass_name(node.name, err)
                cond = _condition_check_expr(err)
                lines.append(f"{i4}if _status == {err.status} and {cond}:")
                lines.append(
                    f"{i4}{ctx.indent_char}return {cls_name}("
                    f"headers=_headers, value=_body)"
                )
                emitted_field_branch = True
        if not emitted_field_branch:
            lines.pop()
    lines.append(f"{i3}return None")

    for err in status_errors:
        cls_name = err_subclass_name(node.name, err)
        lines.append(f"{i2}if _status == {err.status}:")
        lines.append(f"{i3}return {cls_name}(headers=_headers, value=_body)")

    for err in field_errors:
        if not (200 <= err.status < 300):
            cls_name = err_subclass_name(node.name, err)
            cond = _condition_check_expr(err)
            lines.append(
                f"{i2}if _status == {err.status} "
                f"and isinstance(_body, dict) and {cond}:"
            )
            lines.append(
                f"{i3}return {cls_name}(headers=_headers, value=_body)"
            )

    lines.append(
        f"{i2}return UnknownErr(status=_status, headers=_headers, value=_body)"
    )
    return lines


# ---------------------------------------------------------------------------
# Request/fetch method builders
# ---------------------------------------------------------------------------

_PY_PRIM_ANNO: dict[str, str] = {
    "str": "str",
    "int": "int",
    "float": "float",
    "bool": "bool",
}


def _ph_to_py_annotation(ph: PlaceholderSpec) -> tuple[str, str]:
    """Return ``(annotation, default_suffix)``.  Suffix is ``''`` or ``' = None'``."""
    anno = _PY_PRIM_ANNO[ph.type_name]
    if ph.is_array:
        anno = f"List[{anno}]"
    if ph.is_optional:
        return f"Optional[{anno}]", " = None"
    return anno, ""


def render_signature_params(placeholders: list[PlaceholderSpec]) -> str:
    """Build keyword-only parameters clause: ``', *, a: int, b: Optional[str] = None'``."""
    if not placeholders:
        return ""
    required = [p for p in placeholders if not p.is_optional]
    optional = [p for p in placeholders if p.is_optional]
    parts: list[str] = []
    for ph in required + optional:
        anno, default = _ph_to_py_annotation(ph)
        parts.append(f"{ph.name}: {anno}{default}")
    return ", *, " + ", ".join(parts)


def _resolve_ok_payload_type(node: a.RequestConfig) -> str:
    """Return the Python type annotation for the successful payload."""
    if not node.response_schema:
        return "None"
    struct = node.parent
    module = struct.parent if struct is not None else None
    schema_type = f"{to_pascal_case(node.response_schema)}Json"
    if module is not None:
        for n in module.body:
            if isinstance(n, a.JsonDef) and n.name == node.response_schema:
                if n.is_array:
                    return f"List[{schema_type}]"
                break
    return schema_type


def _result_alias_name(raw_name: str) -> str:
    """Convert raw @request name to public Result type alias name."""
    return to_pascal_case(raw_name or "fetch") + "Result"


def emit_result_aliases(struct: a.Struct) -> list[str]:
    """Emit per-endpoint Result type alias definitions for a REST struct."""
    lines: list[str] = []
    for child in struct.body:
        if not isinstance(child, a.RequestConfig):
            continue
        raw_name = child.name or "fetch"
        alias_name = _result_alias_name(raw_name)
        payload = _resolve_ok_payload_type(child)
        err_variants: list[str] = []
        seen: set[str] = set()
        for err in struct.errors:
            cls_name = err_subclass_name(struct.name, err)
            if cls_name not in seen:
                seen.add(cls_name)
                err_variants.append(cls_name)
        parts = [f"Ok[{payload}]", *err_variants, "UnknownErr", "TransportErr"]
        lines.append(f"{alias_name} = Union[" + ", ".join(parts) + "]")
    return lines


def resolve_response_type(node: a.RequestConfig) -> str:
    """Return the Result type alias name for a REST method signature."""
    return _result_alias_name(node.name)


def build_request_method(
    *,
    name: str,
    is_async: bool,
    client_type: str,
    struct_name: str,
    call_args: list[str],
    ph_params: str,
    pre_lines: list[str],
    response_path: str,
    response_join: str,
    i1: str,
    i2: str,
    i3: str,
) -> list[str]:
    """Build a non-REST ``fetch`` / ``async_fetch`` classmethod."""
    async_kw = "async " if is_async else ""
    await_kw = "await " if is_async else ""
    lines: list[str] = [
        f"{i1}@classmethod",
        f'{i1}{async_kw}def {name}(cls, client: {client_type}{ph_params}) -> "{struct_name}":',
    ]
    lines.extend(pre_lines)
    lines.append(f"{i2}_resp = {await_kw}client.request(")
    lines.extend(f"{i3}{a}" for a in call_args)
    lines.append(f"{i2})")
    lines.append(f"{i2}_resp.raise_for_status()")
    if response_path:
        accessor = "".join(f"[{p!r}]" for p in response_path.split("."))
        lines.append(f"{i2}_data = _resp.json()")
        if response_join:
            lines.append(f"{i2}_body = {response_join!r}.join(_data{accessor})")
        else:
            lines.append(f"{i2}_body = _data{accessor}")
    else:
        lines.append(f"{i2}_body = _resp.text")
    lines.append(f"{i2}return cls(_body)")
    return lines


def build_rest_method(
    *,
    node: a.RequestConfig,
    name: str,
    is_async: bool,
    client_type: str,
    call_args: list[str],
    ph_params: str,
    pre_lines: list[str],
    ret_type: str,
    transport_exc: str,
    i1: str,
    i2: str,
    i3: str,
    i4: str,
) -> list[str]:
    """Build a REST ``fetch`` / ``async_fetch`` classmethod with Result return."""
    async_kw = "async " if is_async else ""
    await_kw = "await " if is_async else ""

    lines: list[str] = [
        f"{i1}@classmethod",
        f"{i1}{async_kw}def {name}(cls, client: {client_type}"
        f"{ph_params}) -> {ret_type}:",
    ]
    if node.doc:
        lines.append(f'{i2}"""{node.doc}"""')
    lines.extend(pre_lines)
    lines.append(f"{i2}try:")
    lines.append(f"{i3}_resp = {await_kw}client.request(")
    lines.extend(f"{i4}{a}" for a in call_args)
    lines.append(f"{i3})")
    lines.append(f"{i2}except {transport_exc} as _exc:")
    lines.append(f"{i3}return TransportErr(cause=repr(_exc))")
    lines.append(f"{i2}_status, _headers, _body = _parse_response(_resp)")
    lines.append(f"{i2}_err = cls._dispatch_err(_status, _headers, _body)")
    lines.append(f"{i2}if _err is not None:")
    lines.append(f"{i3}return _err")
    ok_value = "_body" if node.response_schema else "None"
    lines.append(
        f"{i2}return Ok(status=_status, headers=_headers, value={ok_value})"
    )
    return lines
