import json
import re

from ssc_codegen.converters.base import ConverterContext
from ssc_codegen.converters.helpers import to_pascal_case
from ssc_codegen.converters.request_spec import _PH, RequestSpec

import ssc_codegen.ast as a
from ssc_codegen.ast.struct import PlaceholderSpec, _parse_placeholder


# ---------------------------------------------------------------------------
# Cluster 0: Runtime module helpers
# ---------------------------------------------------------------------------

_BASE_UTILITY_LINES: list[str] = [
    "_RE_HEX_ENTITY = re.compile(r'&#x([0-9a-fA-F]+);')",
    "_RE_UNICODE_ENTITY = re.compile(r'\\\\u([0-9a-fA-F]{4})')",
    "_RE_BYTES_ENTITY = re.compile(r'\\\\x([0-9a-fA-F]{2})')",
    "_RE_CHARS_MAP = {'\\b': '\\b', '\\f': '\\f', '\\n': '\\n', '\\r': '\\r', '\\t': '\\t'}",
    "",
    "def repl_map(s: str, rmap: Dict[str, str]) -> str:",
    "    for k, v in rmap.items():",
    "        s = s.replace(k, v)",
    "    return s",
    "",
    "def normalize_text(text: str) -> str:",
    "    return ' '.join(text.split()) if text else \"\"",
    "",
    "class _UnmatchedTableRow:",
    "    pass",
    "",
    "def unescape_text(text: str) -> str:",
    "    s = _html_unescape(text)",
    "    s = _RE_HEX_ENTITY.sub(lambda m: chr(int(m.group(1), 16)), s)",
    "    s = _RE_UNICODE_ENTITY.sub(lambda m: chr(int(m.group(1), 16)), s)",
    "    s = _RE_BYTES_ENTITY.sub(lambda m: chr(int(m.group(1), 16)), s)",
    "    for ch, r in _RE_CHARS_MAP.items():",
    "        s = s.replace(ch, r)",
    "    return s",
    "",
    "if sys.version_info >= (3, 9):",
    "    def rm_prefix(s: str, p: str) -> str:",
    "        return s.removeprefix(p)",
    "",
    "    def rm_suffix(s: str, p: str) -> str:",
    "        return s.removesuffix(p)",
    "",
    "else:",
    "    def rm_prefix(s: str, p: str) -> str:",
    "        return s[len(p):] if s.startswith(p) else s",
    "",
    "    def rm_suffix(s: str, p: str) -> str:",
    "        return s[:-(len(p))] if s.endswith(p) else s",
    "",
    "",
    "UNMATCHED_TABLE_ROW = _UnmatchedTableRow()",
]

_BASE_EXPORT_NAMES: list[str] = [
    "repl_map",
    "normalize_text",
    "_UnmatchedTableRow",
    "unescape_text",
    "rm_prefix",
    "rm_suffix",
    "UNMATCHED_TABLE_ROW",
]


def runtime_export_names(
    node, include_fallback_html: bool = False
) -> list[str]:
    """Names the main module must import from the runtime module."""
    names = list(_BASE_EXPORT_NAMES)
    if include_fallback_html:
        names.append("FALLBACK_HTML_STR")
    if _module_has_rest(node):
        names.extend(
            ["Ok", "Err", "UnknownErr", "TransportErr", "_parse_response"]
        )
    return names


def runtime_module_content(node, include_fallback_html: bool = False) -> str:
    """Full content of the runtime module as a string."""
    lines: list[str] = [
        "# autogenerated runtime helpers — do not edit",
        "import re",
        "import sys",
        "from typing import Dict",
        "from html import unescape as _html_unescape",
    ]
    has_rest = _module_has_rest(node)
    if has_rest:
        lines.extend(
            [
                "from dataclasses import dataclass, field",
                "from typing import Any, Generic, Literal, Mapping, TypeVar",
            ]
        )
    lines.append("")
    lines.append("")
    if include_fallback_html:
        lines.append('FALLBACK_HTML_STR = "<html><body></body></html>"')
        lines.append("")
    lines.extend(_BASE_UTILITY_LINES)
    lines.append("")
    if has_rest:
        lines.extend(rest_utilities(node))
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Cluster A: REST module-level helpers (public API for all py_ converters)
# ---------------------------------------------------------------------------


def _module_has_rest(node) -> bool:
    """True if the given node's Module has any `struct type=rest`."""
    module = node
    while module is not None and not isinstance(module, a.Module):
        module = getattr(module, "parent", None)
    if module is None:
        return False
    return any(
        isinstance(n, a.Struct) and n.is_rest
        for n in getattr(module, "body", [])
    )


def rest_imports(node) -> list[str]:
    """Extra imports required when the module has any `struct type=rest`."""
    if not _module_has_rest(node):
        return []
    return [
        "from dataclasses import dataclass, field",
        "from typing import Generic, Literal, Mapping, TypeVar",
    ]


def http_client_import(ctx: ConverterContext) -> list[str]:
    """Return the import line(s) for the chosen HTTP client, or [] if none."""
    client = ctx.meta.get("http_client", "")
    if client == "requests":
        return ["import requests"]
    if client == "httpx":
        return ["import httpx"]
    return []


def rest_utilities(node) -> list[str]:
    """Ok/Err/UnknownErr/TransportErr + _parse_response block; empty if no REST."""
    if not _module_has_rest(node):
        return []
    return [
        "_T = TypeVar('_T')",
        "_E = TypeVar('_E')",
        "\n",
        "@dataclass(frozen=True)",
        "class Ok(Generic[_T]):",
        "    status: int = 0",
        "    headers: Mapping[str, str] = field(default_factory=dict)",
        "    value: _T = None  # type: ignore[assignment]",
        "    is_ok: Literal[True] = True",
        "\n",
        "@dataclass(frozen=True)",
        "class Err(Generic[_E]):",
        "    status: int = 0",
        "    headers: Mapping[str, str] = field(default_factory=dict)",
        "    value: _E = None  # type: ignore[assignment]",
        "    is_ok: Literal[False] = False",
        "\n",
        "@dataclass(frozen=True)",
        "class UnknownErr(Err[Any]):",
        "    pass",
        "\n",
        "@dataclass(frozen=True)",
        "class TransportErr(Err[None]):",
        "    status: Literal[0] = 0",
        "    cause: str = ''",
        "    value: None = None",
        "    headers: Mapping[str, str] = field(default_factory=dict)",
        "\n\n",
        "def _parse_response(_resp):",
        "    _status = _resp.status_code",
        "    _headers = {k.lower(): v for k, v in _resp.headers.items()}",
        "    try:",
        "        _body = _resp.json()",
        "    except Exception:",
        "        _body = None",
        "    return _status, _headers, _body",
        "\n\n",
    ]


# ---------------------------------------------------------------------------
# Cluster B: REST error helpers
# ---------------------------------------------------------------------------


def _err_subclass_name(struct_name: str, err: a.ErrorResponse) -> str:
    """Naming: `<Struct>Err<Status>[<ConditionKeys>]`."""
    base = f"{to_pascal_case(struct_name)}Err{err.status}"
    if err.conditions:
        for key in err.conditions:
            base += to_pascal_case(key.replace(".", "_").replace("-", "_"))
    return base


def _err_value_type(err: a.ErrorResponse, struct: a.Struct) -> str:
    """Return the typed value annotation for an Err subclass."""
    schema = err.schema_name
    if not schema:
        return "Any"
    type_name = f"{to_pascal_case(schema)}Json"
    module = struct.parent
    if module is not None:
        for n in module.body:
            if isinstance(n, a.JsonDef) and n.name == schema and n.is_array:
                return f"List[{type_name}]"
    return type_name


def _rest_err_union_type(struct: a.Struct) -> str:
    """Return the typed union of all Err variants for _dispatch_err sig."""
    variants: list[str] = []
    seen: set[str] = set()
    for err in struct.errors:
        cls_name = _err_subclass_name(struct.name, err)
        if cls_name not in seen:
            seen.add(cls_name)
            variants.append(cls_name)
    return "Union[" + ", ".join([*variants, "UnknownErr", "None"]) + "]"


def _resolve_path_expr(body_var: str, path: str) -> str:
    """Generate a Python expression that navigates a dot-path into a JSON body.

    Segments: digits → list index, else → dict key via .get().
    """
    parts = path.split(".")
    expr = body_var
    for seg in parts:
        if seg.isdigit():
            expr += f"[{seg}]"
        else:
            expr += f".get({seg!r})"
    return expr


def _condition_check_expr(err: a.ErrorResponse) -> str:
    """Build a compound condition expression for an @error's field conditions."""
    parts = []
    for path, value in err.conditions.items():
        lhs = _resolve_path_expr("_body", path)
        if isinstance(value, bool):
            parts.append(f"{lhs} == {value}")
        elif value is None:
            parts.append(f"{lhs} is None")
        elif isinstance(value, (int, float)):
            parts.append(f"{lhs} == {value}")
        else:
            parts.append(f"{lhs} == {value!r}")
    return " and ".join(parts)


def _emit_dispatch_err_py(node: a.Struct, ctx: ConverterContext) -> list[str]:
    """Emit the `_dispatch_err` @staticmethod lines inside a REST class.

    ctx arrives from a.StructDocstring — already at class-body depth.
    """
    i1 = ctx.indent  # class-body level
    i2 = i1 + ctx.indent_char  # method body
    i3 = i2 + ctx.indent_char  # nested (if ...:)
    i4 = i3 + ctx.indent_char

    errors = node.errors
    status_errors = [e for e in errors if not e.conditions]
    field_errors = [e for e in errors if e.conditions]
    union_type = _rest_err_union_type(node)

    lines: list[str] = [
        f"{i1}@staticmethod",
        f"{i1}def _dispatch_err("
        f"_status: int, _headers: Mapping[str, str], _body: Any"
        f") -> {union_type}:",
        f"{i2}if 200 <= _status < 300:",
    ]

    # 2xx field discriminators check first, inside the 2xx branch
    if field_errors:
        lines.append(f"{i3}if isinstance(_body, dict):")
        emitted_field_branch = False
        for err in field_errors:
            if 200 <= err.status < 300:
                cls_name = _err_subclass_name(node.name, err)
                cond = _condition_check_expr(err)
                lines.append(f"{i4}if _status == {err.status} and {cond}:")
                lines.append(
                    f"{i4}{ctx.indent_char}return {cls_name}("
                    f"headers=_headers, value=_body)"
                )
                emitted_field_branch = True
        if not emitted_field_branch:
            # no 2xx-field errors → drop the isinstance guard
            lines.pop()
    lines.append(f"{i3}return None")

    # non-2xx status routing
    for err in status_errors:
        cls_name = _err_subclass_name(node.name, err)
        lines.append(f"{i2}if _status == {err.status}:")
        lines.append(f"{i3}return {cls_name}(headers=_headers, value=_body)")
    # non-2xx field discriminators (unusual but supported)
    for err in field_errors:
        if not (200 <= err.status < 300):
            cls_name = _err_subclass_name(node.name, err)
            cond = _condition_check_expr(err)
            lines.append(
                f"{i2}if _status == {err.status} "
                f"and isinstance(_body, dict) and {cond}:"
            )
            lines.append(
                f"{i3}return {cls_name}(headers=_headers, value=_body)"
            )

    lines.append(
        f"{i2}return UnknownErr(status=_status, headers=_headers, value=_body)"
    )
    return lines


# ---------------------------------------------------------------------------
# Cluster C: Request/fetch method builders
# ---------------------------------------------------------------------------


_PY_PRIM_ANNO = {"str": "str", "int": "int", "float": "float", "bool": "bool"}


def _ph_to_py_annotation(ph: a.PlaceholderSpec) -> tuple[str, str]:
    """Return (annotation, default_suffix). Suffix is '' or ' = None'."""
    anno = _PY_PRIM_ANNO[ph.type_name]
    if ph.is_array:
        anno = f"List[{anno}]"
    if ph.is_optional:
        return f"Optional[{anno}]", " = None"
    return anno, ""


def _render_signature_params(placeholders: list[a.PlaceholderSpec]) -> str:
    """Build keyword-only parameters clause: ', *, a: int, b: Optional[str] = None'."""
    if not placeholders:
        return ""
    required = [p for p in placeholders if not p.is_optional]
    optional = [p for p in placeholders if p.is_optional]
    parts: list[str] = []
    for ph in required + optional:
        anno, default = _ph_to_py_annotation(ph)
        parts.append(f"{ph.name}: {anno}{default}")
    return ", *, " + ", ".join(parts)


def _resolve_ok_payload_type(node: a.RequestConfig) -> str:
    """Return the Python type annotation for the successful payload."""
    if not node.response_schema:
        return "None"
    struct = node.parent
    module = struct.parent if struct is not None else None
    schema_type = f"{to_pascal_case(node.response_schema)}Json"
    if module is not None:
        for n in module.body:
            if isinstance(n, a.JsonDef) and n.name == node.response_schema:
                if n.is_array:
                    return f"List[{schema_type}]"
                break
    return schema_type


def _result_alias_name(raw_name: str) -> str:
    """Convert raw @request name to public Result type alias name."""
    return to_pascal_case(raw_name or "fetch") + "Result"


def _emit_result_aliases(struct: a.Struct) -> list[str]:
    """Emit per-endpoint Result type alias definitions for a REST struct."""
    lines: list[str] = []
    for child in struct.body:
        if not isinstance(child, a.RequestConfig):
            continue
        raw_name = child.name or "fetch"
        alias_name = _result_alias_name(raw_name)
        payload = _resolve_ok_payload_type(child)
        err_variants: list[str] = []
        seen: set[str] = set()
        for err in struct.errors:
            cls_name = _err_subclass_name(struct.name, err)
            if cls_name not in seen:
                seen.add(cls_name)
                err_variants.append(cls_name)
        parts = [f"Ok[{payload}]", *err_variants, "UnknownErr", "TransportErr"]
        lines.append(f"{alias_name} = Union[" + ", ".join(parts) + "]")
    return lines


def _resolve_response_type(node: a.RequestConfig) -> str:
    """Return the Result type alias name for a REST method signature."""
    return _result_alias_name(node.name)


def _build_request_method(
    *,
    name: str,
    is_async: bool,
    client_type: str,
    struct_name: str,
    call_args: list[str],
    ph_params: str,
    pre_lines: list[str],
    response_path: str,
    response_join: str,
    i1: str,
    i2: str,
    i3: str,
) -> list[str]:
    async_kw = "async " if is_async else ""
    await_kw = "await " if is_async else ""
    lines: list[str] = [
        f"{i1}@classmethod",
        f'{i1}{async_kw}def {name}(cls, client: {client_type}{ph_params}) -> "{struct_name}":',
    ]
    lines.extend(pre_lines)
    lines.append(f"{i2}_resp = {await_kw}client.request(")
    lines.extend(f"{i3}{a}" for a in call_args)
    lines.append(f"{i2})")
    lines.append(f"{i2}_resp.raise_for_status()")
    if response_path:
        accessor = "".join(f"[{p!r}]" for p in response_path.split("."))
        lines.append(f"{i2}_data = _resp.json()")
        if response_join:
            lines.append(f"{i2}_body = {response_join!r}.join(_data{accessor})")
        else:
            lines.append(f"{i2}_body = _data{accessor}")
    else:
        lines.append(f"{i2}_body = _resp.text")
    lines.append(f"{i2}return cls(_body)")
    return lines


def _build_rest_method(
    *,
    node: a.RequestConfig,
    name: str,
    is_async: bool,
    client_type: str,
    call_args: list[str],
    ph_params: str,
    pre_lines: list[str],
    ret_type: str,
    transport_exc: str,
    i1: str,
    i2: str,
    i3: str,
    i4: str,
) -> list[str]:
    async_kw = "async " if is_async else ""
    await_kw = "await " if is_async else ""

    lines: list[str] = [
        f"{i1}@classmethod",
        f"{i1}{async_kw}def {name}(cls, client: {client_type}"
        f"{ph_params}) -> {ret_type}:",
    ]
    if node.doc:
        lines.append(f'{i2}"""{node.doc}"""')
    lines.extend(pre_lines)
    lines.append(f"{i2}try:")
    lines.append(f"{i3}_resp = {await_kw}client.request(")
    lines.extend(f"{i4}{a}" for a in call_args)
    lines.append(f"{i3})")
    lines.append(f"{i2}except {transport_exc} as _exc:")
    lines.append(f"{i3}return TransportErr(cause=repr(_exc))")
    lines.append(f"{i2}_status, _headers, _body = _parse_response(_resp)")
    lines.append(f"{i2}_err = cls._dispatch_err(_status, _headers, _body)")
    lines.append(f"{i2}if _err is not None:")
    lines.append(f"{i3}return _err")
    ok_value = "_body" if node.response_schema else "None"
    lines.append(
        f"{i2}return Ok(status=_status, headers=_headers, value={ok_value})"
    )
    return lines


# ---------------------------------------------------------------------------
# Cluster D: Python code-generation helpers for RequestSpec rendering
# ---------------------------------------------------------------------------

_STYLE_SEPARATOR = {"csv": ",", "pipe": "|", "space": " "}


def _render_array_join(ph: PlaceholderSpec) -> str:
    """Array placeholder → Python expression producing a joined string."""
    sep = _STYLE_SEPARATOR[ph.style or "csv"]
    return f"{sep!r}.join(str(_x) for _x in {ph.name})"


def render_value(v: str) -> str:
    """
    Convert a RequestSpec string value to a Python code fragment.

    "{{query}}"          → query             (bare variable; scalar or repeat-array)
    "{{tags:int[]|csv}}" → ",".join(...)     (array with explicit separator)
    "Bearer {{token}}"   → f"Bearer {token}" (f-string, scalars only)
    "Mozilla/5.0"        → "Mozilla/5.0"     (string literal)
    """
    if m := _PH.fullmatch(v):
        ph = _parse_placeholder(m)
        if ph.is_array and ph.style in ("csv", "pipe", "space"):
            return _render_array_join(ph)
        return ph.name
    if _PH.search(v):
        return f'f"{_escape_fstring(v)}"'
    return repr(v)


def _escape_fstring(template: str) -> str:
    """
    Convert a placeholder template string to an f-string body.

    Non-placeholder { and } are doubled (escaped); {{name}} → {name}.
    """
    result = []
    i = 0
    while i < len(template):
        if template[i : i + 2] == "{{" and _PH.match(template, i):
            m = _PH.match(template, i)
            result.append("{" + m.group(1) + "}")
            i = m.end()
        elif template[i] in "{}":
            result.append(template[i] * 2)  # escape lone brace
            i += 1
        else:
            result.append(template[i])
            i += 1
    return "".join(result)


def render_dict(d: dict[str, str], *, indent: str = "") -> str:
    """Render a flat string dict as a Python dict literal."""
    if not d:
        return "{}"
    inner = ", ".join(f"{k!r}: {render_value(str(v))}" for k, v in d.items())
    return "{" + inner + "}"


def _dict_entry_placeholder(v: str) -> PlaceholderSpec | None:
    """Return the PlaceholderSpec if value is a fullmatch placeholder, else None."""
    m = _PH.fullmatch(str(v))
    return _parse_placeholder(m) if m else None


def dict_needs_builder(d: dict[str, str]) -> bool:
    """
    True when dict rendering requires a multi-line local builder.

    Needed if any value is an optional fullmatch placeholder (conditional drop)
    or uses bracket-style serialization (key rewrite).
    """
    for v in d.values():
        ph = _dict_entry_placeholder(str(v))
        if ph is None:
            continue
        if ph.is_optional:
            return True
        if ph.is_array and ph.style == "bracket":
            return True
    return False


def emit_dict_builder(
    varname: str, d: dict[str, str], indent: str
) -> list[str]:
    """
    Emit Python lines building a local dict that supports optional drops and
    bracket key rewrites:

        _params = {}
        if q is not None:
            _params["q"] = q
        _params["tags[]"] = tags
        _params["limit"] = limit
    """
    lines = [f"{indent}{varname}: dict = {{}}"]
    for key, value in d.items():
        value = str(value)
        ph = _dict_entry_placeholder(value)
        if ph is None:
            lines.append(f"{indent}{varname}[{key!r}] = {render_value(value)}")
            continue
        effective_key = (
            f"{key}[]" if (ph.is_array and ph.style == "bracket") else key
        )
        expr = render_value(value)
        if ph.is_optional:
            lines.append(f"{indent}if {ph.name} is not None:")
            lines.append(f"{indent}    {varname}[{effective_key!r}] = {expr}")
        else:
            lines.append(f"{indent}{varname}[{effective_key!r}] = {expr}")
    return lines


def render_json_body(raw: str) -> str:
    """
    Render a JSON body template (with {{placeholders}}) as a Python dict/list
    literal expression suitable for `requests(json=...)` / `httpx(json=...)`.
    """
    from ssc_codegen.converters.request_spec import _validate_json_body

    _validate_json_body(raw)

    sentinels: dict[str, str] = {}
    out: list[str] = []
    i = 0
    n = len(raw)
    in_string = False
    while i < n:
        if raw[i : i + 2] == "{{":
            m = _PH.match(raw, i)
            if m is not None:
                name = _parse_placeholder(m).name
                key = f"__SSC_PH_{len(sentinels)}__"
                sentinels[key] = name
                out.append(key if in_string else '"' + key + '"')
                i = m.end()
                continue
        ch = raw[i]
        if ch == "\\" and i + 1 < n:
            out.append(raw[i : i + 2])
            i += 2
            continue
        if ch == '"':
            in_string = not in_string
        out.append(ch)
        i += 1
    substituted = "".join(out)
    parsed = json.loads(substituted)
    sentinel_re = re.compile(r"__SSC_PH_\d+__")

    def _emit(v: object) -> str:
        if v is None:
            return "None"
        if isinstance(v, bool):
            return "True" if v else "False"
        if isinstance(v, (int, float)):
            return repr(v)
        if isinstance(v, str):
            if v in sentinels:
                return sentinels[v]
            if sentinel_re.search(v):

                def _fmt(m: re.Match) -> str:
                    return "{" + sentinels[m.group(0)] + "}"

                escaped = v.replace("\\", "\\\\").replace("'", "\\'")
                escaped = escaped.replace("{", "{{").replace("}", "}}")
                body = sentinel_re.sub(_fmt, escaped)
                return "f'" + body + "'"
            return repr(v)
        if isinstance(v, dict):
            items = ", ".join(f"{k!r}: {_emit(val)}" for k, val in v.items())
            return "{" + items + "}"
        if isinstance(v, list):
            items = ", ".join(_emit(x) for x in v)
            return "[" + items + "]"
        raise TypeError(f"unsupported JSON body element: {type(v).__name__}")

    return _emit(parsed)


def render_body(spec: RequestSpec) -> tuple[str, str] | None:
    """
    Return the Python code fragment for the body argument, or None if empty.

    Returns a (kwarg_name, code) tuple, e.g. ("json", '{"id": id}').
    """
    if spec.body_kind == "empty" or spec.body is None:
        return None
    if spec.body_kind == "json":
        return ("json", render_json_body(str(spec.body)))
    if spec.body_kind == "form":
        assert isinstance(spec.body, dict)
        return ("data", render_dict(spec.body))
    # raw
    return ("data", render_value(str(spec.body)))
