from abc import abstractmethod

from ssc_codegen.ast import (
    Node,
    Imports,
    Module,
    ImportsRest,
    Docstring,
    Utilities,
    JsonDef,
    JsonDefField,
    TypeDef,
    TypeDefField,
    StructItem,
    StructList,
    StructFlatList,
    StructDict,
    StructTable,
    StructRest,
    StructDocstring,
    StartParse,
    Init,
    InitField,
    Field,
    PreValidate,
    CheckMethod,
    SplitDoc,
    Key,
    Value,
    TableConfig,
    TableMatchKey,
    TableRow,
    MethodRest,
    MethodFetch,
    ErrorResponse,
    CssSelect,
    CssSelectAll,
    XpathSelect,
    XpathSelectAll,
    CssRemove,
    XpathRemove,
    Attr,
    Text,
    Raw,
    Trim,
    Ltrim,
    Rtrim,
    RmPrefix,
    RmSuffix,
    RmPrefixSuffix,
    Fmt,
    Repl,
    ReplMap,
    Lower,
    Upper,
    Split,
    Join,
    NormalizeSpace,
    Unescape,
    Re,
    ReAll,
    ReSub,
    Index,
    Slice,
    Len,
    Unique,
    ToInt,
    ToFloat,
    ToBool,
    Jsonify,
    Nested,
    Self,
    TransformCall,
    Return,
    FallbackStart,
    FallbackEnd,
    Filter,
    Assert,
    Match,
    LogicAnd,
    LogicNot,
    LogicOr,
    PredCss,
    PredXpath,
    PredHasAttr,
    PredAttrContains,
    PredAttrStarts,
    PredAttrEnds,
    PredAttrEq,
    PredAttrNe,
    PredAttrRe,
    PredTextContains,
    PredTextStarts,
    PredTextEnds,
    PredTextRe,
    PredContains,
    PredEq,
    PredNe,
    PredStarts,
    PredEnds,
    PredCountEq,
    PredCountGt,
    PredCountLt,
    PredCountNe,
    PredCountGe,
    PredCountLe,
    PredCountRange,
    PredIn,
    PredGe,
    PredGt,
    PredLe,
    PredLt,
    PredRe,
    PredReAll,
    PredReAny,
    CodeEndHook,
    CodeStartHook
)
from ssc_codegen.converters.base import ConverterContext

# TODO:
# Module - store dosctring
# 1 Struct - unify
# 1.1 Strcut - store docstring


class Visitor:
    def __init__(self, var_name: str = "v", indent: str = " " * 4) -> None:
        pass

    # === CORE ===
    def visit(self, nodes: list[Node], ctx: ConverterContext):
        """Универсальный базовый AST визитор. Обходит всё AST дерево и передаёт ноды в дочений код
        """

    def convert(self):
        """Entrypoint генерации AST в конечный код"""

    # TODO: не хочется дублировать хуки pre_*, post_*
    # может быть эмулировать эту фичу через yield?

    # NODE APIS. need override
    @abstractmethod
    def std_lib(self, name: str):
        """Генерация стандартной библиотеки, чтобы упростить генерацию выражений.
        
        Код может распаковываться Inline в модуль

        Примечание: не реализовывать эквивалентный std код, если операция нативно 
        в одну строку транслируется из AST
        """

    @abstractmethod
    def visit_module(self, node: Module, ctx: ConverterContext):
        """
        автоматически генерирует AST 
        
        Корневая нода модуля-парсера
        1. в начале файла добавить комментарий: "autogenerated by ssc-gen DO NOT EDIT"
        2. если есть docstring - транспилировать
        """

    @abstractmethod
    def visit_docstring(self, node: Docstring):
        """TODO: DELETE THIS NODE - add to Module AST"""

    @abstractmethod
    def visit_imports(self, node: Imports, ctx: ConverterContext):
        """
        автоматически генерирует AST 

        Генерация базовых строк импортов
        
        1. при генерации std модуля - делать его import
        2. если inline генерация std - добавлять его импорты
        """

    @abstractmethod
    def visit_rest_imports(self, node: ImportsRest, ctx: ConverterContext):
        # TODO: move to single Imports node???
        """
        автоматически генерирует AST 

        Генерация http rest specific строк импортов

        1. при генерации std модуля - делать его import
        2. если inline генерация std - добавлять его импорты
        """

    @abstractmethod
    def visit_utilities(self, node: Utilities, ctx: ConverterContext):
        """
        автоматически генерирует AST 

        Используется для генерации inline std кода если не генерируется отдельный модуль
        """

    @abstractmethod
    def visit_code_start_hook(self, node: CodeStartHook, ctx: ConverterContext):
        """
        автоматически генерирует AST 

        Специальный AST-hook: после ноды Utilities можно вставить дополнительный код

        Если не нужно - возвращайте None
        """

    @abstractmethod
    def visit_code_end_hook(self, node: CodeEndHook, ctx: ConverterContext):
        """
        автоматически генерирует AST 

        Специальный AST-hook: в конце файла можно вставить дополнительный код

        Если не нужно - возвращайте None
        """

    # === TYPES ===
    @abstractmethod
    def visit_jsondef(self, node: JsonDef, ctx: ConverterContext):
        """
        KDL: `json <name> { ... }` 

        Генерация struct/type annotation для типизации json данных
        """

    @abstractmethod
    def visit_jsondef_field(self, node: JsonDefField, ctx: ConverterContext):
        """
        KDL: `json <name> { field... }`

        Генерация поля с  типизацией для JsonDef структуры.
        генерировать тип на основе информации из `node.ret`
        """

    @abstractmethod
    def visit_typedef(self, node: TypeDef, ctx: ConverterContext):
        """
        автоматически генерирует AST на базе non-rest `struct` 

        Генерация struct/type annotation для типизации данных для html parser структур
        """

    @abstractmethod
    def visit_typedef_field(self, node: TypeDefField, ctx: ConverterContext):
        """
        автоматически генерирует AST на базе non-rest `struct` 

        Генерация поля с  типизацией для TypeDef структуры.
        генерировать тип на основе информации из `node.ret`
        """

    # === STRUCT ===
    # TODO: unify to single struct node???
    @abstractmethod
    def visit_struct_item(self, node: StructItem, ctx: ConverterContext):
        """
        KDL: `struct <name> { ... }| (item)struct <name> { ... }| sturct <name> type=item { ... }`

        Генерация header структуры/класса

        если есть документация - сегенерировать
        """

    @abstractmethod
    def visit_struct_list(self, node: StructList, ctx: ConverterContext):
        """
        KDL: `struct <name> type=list { ... }| (list)struct <name> { ... }`

        Генерация header структуры/класса

        если есть документация - сегенерировать
        """
    
    @abstractmethod
    def visit_struct_flat_list(
        self, node: StructFlatList, ctx: ConverterContext
    ):
        """
        KDL: `struct <name> type=flat { ... }| (flat)struct <name> { ... }`

        Генерация header структуры/класса

        если есть документация - сегенерировать
        """

    @abstractmethod
    def visit_struct_dict(self, node: StructDict, cxt: ConverterContext):
        """
        KDL: `struct <name> type=dict { ... }| (dict)struct <name> { ... }`

        Генерация header структуры/класса

        если есть документация - сегенерировать
        """
    
    @abstractmethod
    def visit_struct_table(self, node: StructTable, ctx: ConverterContext):
        """
        KDL: `struct <name> type=table { ... }| (table)struct <name> { ... }`

        Генерация header структуры/класса
        
        если есть документация - сегенерировать
        """
    
    @abstractmethod
    def visit_struct_rest(self, node: StructRest, ctx: ConverterContext):
        """
        KDL: `struct <name> type=rest { ... }| (rest)struct <name> { ... }`
        Генерация header структуры/класса для вызова REST методов

        если есть документация - сегенерировать
        """
    
    @abstractmethod
    def visit_struct_docstring(
        self, node: StructDocstring, ctx: ConverterContext
    ):
        """DEPRECATE: move to Struct node as property

        rationale:
            - python - docstring contains down
            - js, go, etc - docstring contains upper
        """
        pass

    @abstractmethod
    def visit_init(self, node: Init, ctx: ConverterContext):
        """
        KDL: 
            ```
            // vvvvv
            @init {
            
                <name> {
                    ...
                    }
            }
            ```
        
        Генерация публичного конструктора для структуры/класса
        
        1. хранит DOM-like Document/Element переданного html 
        2. если есть `InitField` - предварительно вызывать и положить в конструктор
        """

    @abstractmethod
    def visit_init_field(self, node: InitField, ctx: ConverterContext):
        """
        
        KDL: 
            ```
            @init {
             // vvvvv
                <name> {
                    ...
                    }
            }
            ```
        
        Header приватного метода структуры, в котором предварительно извлекается значение
        
        """

    @abstractmethod
    def visit_field(self, node: Field, ctx: ConverterContext):
        """
        
        KDL: `struct Foo { <name> { ... }... }`
        Header приватного  метода структуры, в котором при запуске StartParse вычисляется
        """

    @abstractmethod
    def visit_pre_validate(self, node: PreValidate, ctx: ConverterContext):
        """
        
        KDL: `@pre-validate { ... }`

        Header приватного метода структуры, в котором до запуска валидирует значение.
        - Не модифицируется документ
        - Предполагается, что это поле применяет `assert` блоки. 
        - Если проверка не проходит - код возвращает ошибку
        """

    @abstractmethod
    def visit_check_method(self, node: CheckMethod, ctx: ConverterContext):
        """
        
        KDL: `@check <name> { ... }`

        Header публичного метода структуры, который можно вызывать для базовых проверок
        - всегда возвращает boolean значение
        """

    @abstractmethod
    def visit_split_doc(self, node: SplitDoc, ctx: ConverterContext):
        """
        
        KDL: `@split-doc { ... }`

        Header приватного метода структуры, который разделяет документ на части по селектору (на карточки, например)
        - всегда возвращает TypeInfo(Document, is_array=True)
        """

    @abstractmethod
    def visit_key(self, node: Key, ctx: ConverterContext):
        """
        KDL: `@key { ... }`

        Header приватного метода для StructDict, который применяет как ключ. Всегда возвращает STRING
        """

    @abstractmethod
    def visit_value(self, node: Value, ctx: ConverterContext):
        """
        KDL: `@value { ... }`

        1. Header приватного метода для StructDict, который применяет как значение.
        2. (ADHOC) Header приватного метода для StructTable, который извлекает значение из строки таблицы.
        """

    @abstractmethod
    def visit_table_config(self, node: TableConfig, ctx: ConverterContext):
        """
        KDL: `@table { ... }`
        Header приватного метода для StructTable, который указывает селект на <table>-like элемент
        """

    @abstractmethod
    def visit_table_match_key(self, node: TableMatchKey, ctx: ConverterContext):
        """
        KDL: `@match { ... }`

        Header приватного метода для StructTable - извлекает значение "ключ" из таблицы. Всегда возвращает STRING
        Используется для сопоставления значений для html таблиц.
        """

    @abstractmethod
    def visit_table_row(self, node: TableRow, ctx: ConverterContext):
        """
        KDL: `@rows { ... }`

        Header приватного метода для извлечения всех строк из таблицы. Всегда возвращает DOCUMENT (is_array=True)
        """

    @abstractmethod
    def visit_method_fetch(self, node: MethodFetch, ctx: ConverterContext):
        """
        KDL: `@request ...`

        Для HTML parser структур. опциональный classmethod конструктор, который делает http запрос и инициализирует.

        - не настраивает http client - он передаётся первым аргументом, нужно настраивать извне. 
        сигнатура (HttpClient, *, params...)
        """

    @abstractmethod
    def visit_method_rest(self, node: MethodRest, ctx: ConverterContext):
        """
        KDL: `@request ...`

        Для REST-API структур, добавляет метод отправки запроса, возвращает json

        - не настраивает http client - он передаётся первым аргументом, нужно настраивать извне. 
        сигнатура (HttpClient, *, params...)
        - TIP: для простоты реализации, применения и портируемости, рекомендуется возвращать и генерировать monad-like структуры
        """
    @abstractmethod
    def visit_error_response(self, node: ErrorResponse, ctx: ConverterContext):
        """
        Response Error????
        """

    @abstractmethod
    def visit_start_parse(self, node: StartParse, ctx: ConverterContext):
        """
        автоматически генерирует AST 

        Header публичного метода start_parse, startParse, который запускает парсер и возвращает структуру

        Требуется генерировать header + код

        Стратегии (pseudocode):

        StructItem:
            ```
            fn start_parse() {
                PreValidate(document) // if defined
                result = {}
                result[field_name1] = ParseField1(document)
                result[field_name2] = ParseField2(document)
                ...
                return result
            }
            ```
        StructList:
            ```
            fn start_parse() {
                PreValidate(document) // if defined
                results = []
                parts = SplitDoc(document)
                result = {}
                for part in parts {
                    result[field_name1] = ParseField1(document)
                    result[field_name2] = ParseField2(document)
                    ...
                    results.append(result)
                    result = {}
                }
                return results
            }
            ```
        StructDict (key, value - stable keys, allow hardcode):
            ```
            fn start_parse() {
                PreValidate(document) // if defined
                result = {}
                parts = SplitDoc(document)
                for part in parts {
                    key = ParseKey(part)
                    value = ParseValue(part)
                    result[key] = value
                }
                return result
            }
            ```

        StructFlatList (allow STRING only):
            ```
            fn start_parse() {
                PreValidate(document) // if defined
                results = []
                // in codegen: allow check return type and simplify code
                result1: string = ParseField1(document)
                results.append(result1)
                result2: string[] = ParseField2(document)
                results.extend(results2)
                ...
                // finally, drop duplicates.
                // dont remember check keep_order flag: if true - implement algorith with keep ordering all colleceted elements
                results = list(set(results))
                return results
            }
            ```
        StructTable:
            - TIP: null/None - применяется в проекте, для проверок используйте SENTINEL объект для проверок

            ```
            NOT_VALID_ROW = Sentinel()

            fn start_parse() {
                PreValidate(document) // if defined
                results = {}

                table = TableConfig(document)  // @table
                rows = TableRow(table)   // @rows
                for row in rows {
                    field1 = ParseField1(row)
                    // test with sentinel object
                    if field1 != NOT_VALID_ROW {
                        results[field_name1] = field1
                        continue
                    }
                    // next row tests if not passed
                    field2 = ParseField2(row)
                    if field2 != NOT_VALID_ROW {
                        results[field_name2] = field1
                        continue
                    }
                    ...
                }
                return results
            }
            ```

        StructRest: not used this method and not generate AST node, skip
        """
        # TODO: research generate transform callers. rationale: simplify generate???
        # StartParseSetup
        # CallPreValidate
        # CallStartParse
        # Return???


    # === EXPRESSIONS ===

    # === SELECTORS ===
    @abstractmethod
    def visit_css_select(self, node: CssSelect, ctx: ConverterContext):
        """
        kdl: `css query | css { query1; query2... }`

        TYPES:
            - DOCUMENT -> DOCUMENT

        - извлечь первый элемент по CSS селектору. 
        - если передано несколько query, то возвращает элемент из первого найденного селектора
        - не проверять на 3 или 4 стандарт - зависит от целевой библиотеки.
        - null/None обрабатывать не нужно
        """

    @abstractmethod
    def visit_css_select_all(self, node: CssSelectAll, ctx: ConverterContext):
        """
        kdl: `css-all query | css-all { query1; query2... }`

        TYPES:
            - DOCUMENT -> DOCUMENT[]
        
        - извлечь все элементы по CSS селектору. 
        - если передано несколько query, то возвращает элементы из первого найденного селектора
        - не проверять на 3 или 4 стандарт - зависит от целевой библиотеки.
        - null/None обрабатывать не нужно
        """

    @abstractmethod
    def visit_css_remove(self, node: CssRemove, ctx: ConverterContext):
        """
        kdl: `css-remove query`

        TYPES:
            - DOCUMENT -> DOCUMENT

        - удаляет из корневого документа элемент по CSS селектору
        - даёт side effect
        - в идеале, дочерние элементы удалять тоже (не проверено)
        - эта операция обычно ничего не возвращает, не забудьте присвоить новую переменную
        """

    @abstractmethod
    def visit_xpath_select(self, node: XpathSelect, ctx: ConverterContext):
        """
        kdl: `xpath query | xpath { query1; query2... }`

        TYPES:
            - DOCUMENT -> DOCUMENT

        - извлечь первый элемент по XPATH селектору. 
        - если передано несколько query, то возвращает элемент из первого найденного селектора
        - null/None обрабатывать не нужно
        """

    @abstractmethod
    def visit_xpath_select_all(
        self, node: XpathSelectAll, ctx: ConverterContext
    ):
        """
        kdl: `xpath-all query | xpath-all { query1; query2... }`

        TYPES:
            - DOCUMENT -> DOCUMENT[]

        - извлечь все элементы по XPATH селектору. 
        - если передано несколько query, то возвращает элементы из первого найденного селектора
        - null/None обрабатывать не нужно
        """

    @abstractmethod
    def visit_xpath_remove(self, node: XpathRemove, ctx: ConverterContext):
        """
        kdl: `xpath-remove query`

        TYPES:
            - DOCUMENT -> DOCUMENT

        - удаляет из корневого документа элемент по XPATH селектору
        - даёт side effect
        - в идеале, дочерние элементы удалять тоже (не проверено)
        - эта операция обычно ничего не возвращает, не забудьте присвоить новую переменную
        """

    @abstractmethod
    def visit_text(self, node: Text, ctx: ConverterContext):
        """
        kdl: `text`

        TYPES:
            - DOCUMENT -> STRING
            - DOCUMENT[] -> STRING[]

        - извлечь текст из элемента
        - DOCUMENT:
        - если тип DOCUMENT(array=true) - излечь из каждого элемента и вернуть плоский список 
        """

    @abstractmethod
    def visit_raw(self, node: Raw, ctx: ConverterContext):
        """
        kdl: `raw`

        TYPES:
            - DOCUMENT -> STRING
            - DOCUMENT[] -> STRING[]

        - извлечь сырой html из элемента (htmlOuter, дочерние элементы тоже)
        - если тип DOCUMENT(array=true) - излечь из каждого элемента и вернуть плоский список 
        """

    @abstractmethod
    def visit_attr(self, node: Attr, ctx: ConverterContext):
        """
        kdl: `attr <name>...`

        TYPES:
            - DOCUMENT -> STRING
            - DOCUMENT[] -> STRING[]

        - извлечь атрибут по ключу
        - DOCUMENT:
            - если 1 ключ - брать на прямую, разрешено падение с ошибкой
            - если >1 ключа - проверять наличие ключа, извлекать все атрибуты (STRING(array=true))
        - DOCUMENT(array=true)
            - если 1 ключ - проверять наличие ключа извлекать из всех элементов
            - если >2 ключа - роверять наличие ключа. **все найденные атрибуты собирать в плоский список**
        """

    # === STRING ===
    @abstractmethod
    def visit_trim(self, node: Trim, ctx: ConverterContext):
        """
        kdl: `trim <chars>`

        TYPES:
            - STRING -> STRING
            - STRING[] -> STRING[]

        - удалить символы СЛЕВА и СПРАВА
        - если <chars> пустой - удалить все пробельный символы
        """
    
    @abstractmethod
    def visit_l_trim(self, node: Ltrim, ctx: ConverterContext):
        """
        kdl: `ltrim <chars>`

        TYPES:
            - STRING -> STRING
            - STRING[] -> STRING[]

        - удалить символы СЛЕВА
        - если <chars> пустой - удалить все пробельный символы
        """

    @abstractmethod
    def visit_r_trim(self, node: Rtrim, ctx: ConverterContext):
        """
        kdl: `rtrim <chars>`

        TYPES:
            - STRING -> STRING
            - STRING[] -> STRING[]

        - удалить символы СПРАВА
        - если <chars> пустой - удалить все пробельный символы
        - STRING(array) - для всех элементов
        """

    @abstractmethod
    def visit_rm_prefix(self, node: RmPrefix, ctx: ConverterContext):
        """
        kdl: `rm-prefix <substr>`

        TYPES:
            - STRING -> STRING
            - STRING[] -> STRING[]

        - удалить префикс по подстроке
        - STRING(array) - для всех элементов
        """

    @abstractmethod
    def visit_rm_suffix(self, node: RmSuffix, ctx: ConverterContext):
        """
        kdl: `rm-suffix <substr>`

        TYPES:
            - STRING -> STRING
            - STRING[] -> STRING[]

        - удалить суффикс по подстроке
        - STRING(array) - для всех элементов
        """

    @abstractmethod
    def visit_rm_prefix_suffix(
        self, node: RmPrefixSuffix, ctx: ConverterContext
    ):
        """
        kdl: `rm-prefix-suffix <substr>`

        TYPES:
            - STRING -> STRING
            - STRING[] -> STRING[]

        - удалить префикс, потом суффикс по подстроке
        """

    @abstractmethod
    def visit_format(self, node: Fmt, ctx: ConverterContext):
        """
        kdl: `fmt <template>`

        TYPES:
            - STRING -> STRING
            - STRING[] -> STRING[]

        - подставляет предыдущее значение по шаблону
        - маркер-шаблон "дырка" = `{{}}` - заменяйте на его эквивалент
        """

    @abstractmethod
    def visit_repl(self, node: Repl, ctx: ConverterContext):
        """
        kdl: `repl <old> <new>`

        TYPES:
            - STRING -> STRING
            - STRING[] -> STRING[]

        - замена подстроки.
        - заменяет все вхождения, нет лимита
        - STRING(array) - для всех элементов
        """

    @abstractmethod
    def visit_repl_map(self, node: ReplMap, ctx: ConverterContext):
        """
        kdl: `repl {<old1> <new1>; <old2> <new2>}`

        TYPES:
            - STRING -> STRING
            - STRING[] -> STRING[]

        - замена набор подстрок.
        - заменяет все вхождения, нет лимита
        - STRING(array) - для всех элементов
        """

    @abstractmethod
    def visit_lower(self, node: Lower, ctx: ConverterContext):
        """
        kdl: `lower`

        TYPES:
            - STRING -> STRING
            - STRING[] -> STRING[]

        - перевод в нижний регистр
        - STRING(array) - для всех элементов
        """

    @abstractmethod
    def visit_upper(self, node: Upper, ctx: ConverterContext):
        """
        kdl: `upper`

        TYPES:
            - STRING -> STRING
            - STRING[] -> STRING[]

        - перевод в верхний регистр
        - STRING(array) - для всех элементов
        """

    @abstractmethod
    def visit_split(self, node: Split, ctx: ConverterContext):
        """
        kdl: `split <sep>`

        TYPES:
            - STRING -> STRING[]

        - разделение по подстроке
        """

    @abstractmethod
    def visit_join(self, node: Join, ctx: ConverterContext):
        """
        kdl: `join <sep>`

        TYPES:
            - STRING[] -> STRING

        - объединение в одну строку через символ `sep`
        """

    @abstractmethod
    def visit_norm_space(self, node: NormalizeSpace, ctx: ConverterContext):
        """
        kdl: `normalize-space`

        TYPES:
            - STRING[] -> STRING[]
            - STRING -> STRING

        - нормализация пробелов. 
            - Удаление всех пробелова СЛЕВА и СПРАВА.
            - длинные пробелы заменяются на короткие
        
        псевдокод реализации std для вызова:

        ```
         def normalize_text(text: str) -> str:
            return ' '.join(text.split()) if text else ""
        ```
        """

    @abstractmethod
    def visit_unescape(self, node: Unescape, ctx: ConverterContext):
        """
        kdl: `unescape`

        TYPES:
            - STRING[] -> STRING[]
            - STRING -> STRING

        - универсальный unescape. ВСЁ делает unescape
        
        псевдокод std реализации для вызова:

        ```
        import re
        from html import unescape

        RE_HEX_ENTITY = re.compile(r'&#x([0-9a-fA-F]+);')
        RE_UNICODE_ENTITY = re.compile(r'\\\\u([0-9a-fA-F]{4})')
        RE_BYTES_ENTITY = re.compile(r'\\\\x([0-9a-fA-F]{2})')
        RE_CHARS_MAP = {'\\b': '\\b', '\\f': '\\f', '\\n': '\\n', '\\r': '\\r', '\\t': '\\t'}

        def std_unescape(text: str) -> str
            s = unescape(text)
            s = _RE_HEX_ENTITY.sub(lambda m: chr(int(m.group(1), 16)), s)
            s = _RE_UNICODE_ENTITY.sub(lambda m: chr(int(m.group(1), 16)), s)
            s = _RE_BYTES_ENTITY.sub(lambda m: chr(int(m.group(1), 16)), s)
            for ch, r in _RE_CHARS_MAP.items():
                s = s.replace(ch, r)
            return s
        ```
        """

    # === REGEX ===

    @abstractmethod
    def visit_re(self, node: Re, ctx: ConverterContext):
        """
        kdl: `re <pattern>`

        TYPES:
            - STRING -> STRING

        - захват **только одной группы**
        - базовый синтаксис PCRE без сложных фичей как lookahead, lookbehind, named groups
        """

    @abstractmethod
    def visit_re_all(self, node: ReAll, ctx: ConverterContext):
        """
        kdl: `re-all <pattern>`

        TYPES:
            - STRING -> STRING[]

        - захват **только одной группы**
        - базовый синтаксис PCRE без сложных фичей как lookahead, lookbehind, named groups
        """

    @abstractmethod
    def visit_re_sub(self, node: ReSub, ctx: ConverterContext):
        """
        kdl: `re-sub <pattern> <repl>`

        TYPES:
            - STRING[] -> STRING[]
            - STRING -> STRING

        - не учитывает группы захвата
        - базовый синтаксис PCRE без сложных фичей как lookahead, lookbehind, named groups
        - limit нет - заменяет всё по выражению
        """

    # === ARRAY ===
    @abstractmethod
    def visit_index(self, node: Index, ctx: ConverterContext):
        """
        kdl: `index <N>`
        aliases:
            `first` == `index 0`
            `last` == `index -1`

        TYPES:
            - AUTO[] -> AUTO

        - начинается индекс с 0
        - поддерживает отрицательные индексы. Если target не поддерживает - транслируйте в `PRV[len(PRV) - N]`
        """

    @abstractmethod
    def visit_slice(self, node: Slice, ctx: ConverterContext):
        """
        kdl: `slice <START> <END>`

        TYPES:
            - AUTO[] -> AUTO[]

        TODO (мало тестов, почти не применяется на практике)
        """

    @abstractmethod
    def visit_len(self, node: Len, ctx: ConverterContext):
        """
        kdl: `len`

        TYPES:
            - AUTO[] -> INT

        - получение длинны предыдущего элемента
        - работает только с is_array=true, не берёт длину строк
        """

    @abstractmethod
    def visit_unique(self, node: Unique, ctx: ConverterContext):
        """
        kdl: `unique`

        TYPES:
            - STRING[] -> STRING[]

        - удаление дубликатов
        - если keep_order=True - нужно использовать алгоритм, который гарантирует порядок элементов
        """

    # === CASTS ===
    @abstractmethod
    def visit_to_int(self, node: ToInt, ctx: ConverterContext):
        """
        kdl: `to-int`

        TYPES:
            - STRING[] -> INT[]
            - STRING -> INT

        - cast в int64 (int32 для x86)
        - не валидирует ввод, он на стороне пользователя
        - STRING(array)
        """

    @abstractmethod
    def visit_to_float(self, node: ToFloat, ctx: ConverterContext):
        """
        kdl: `to-float`

        TYPES:
            - STRING[] -> FLOAT[]
            - STRING -> FLOAT

        - cast в float64 (float32 для x86)
        - не валидирует ввод, он на стороне пользователя
        - STRING(array)
        """

    @abstractmethod
    def visit_to_bool(self, node: ToBool, ctx: ConverterContext):
        """
        kdl: `to-bool`

        TYPES:
            - AUTO -> BOOL
            - AUTO[] -> BOOL

        - cast в boolean
        - возвращать false:
            - null/None
            - пустая строка
            - пустой массив
            - int == 0
        - в остальных случаях true
        """


    @abstractmethod
    def visit_jsonify(self, node: Jsonify, ctx: ConverterContext):
        """
        kdl: `jsonify <JsonStruct> <path?>`

        TYPES:
            - STRING -> JSON

        - не валидирует ввод json-like строки
        - если указан path: сначала из него извлечь json объект
        - потом аннотировать/среиализовать как JsonStruct
        - всегда последняя операция
        """

    @abstractmethod
    def visit_nested(self, node: Nested, ctx: ConverterContext):
        """
        kdl: `nested <Struct>`

        TYPES:
            - DOCUMENT -> NESTED

        - всегда первый вызов (тип DOCUMENT)
        - другие expr не применяются
        - вызывает конструктор вложенного парсера, потом возвращает его значение
        """

    # === CONTROLS ===
    @abstractmethod
    def visit_self(self, node: Self, ctx: ConverterContext):
        """
        kdl: `self <init-field-name>` (deprecated)
        kdl: `@<init-field-name>`

        TYPES:
            - DOCUMENT -> AUTO

        - всегда первый
        - копирует предвычисленное значение из этого поля (это тип данных - что вернул init-field)
        """

    def visit_transform_call(self, node: TransformCall, ctx: ConverterContext):
        # DEPRECATED: delete (difficult, unstable API for code parts injection)
        pass
    
    @abstractmethod
    def visit_return(self, node: Return, ctx: ConverterContext):
        """
        AST AUTO generated

        - последнее значение в поле возвращается, автоматически определяет тип
        - для PreValidate оно всегда null/None (ничего не возвращает)
        """

    @abstractmethod
    def visit_fallback_start(self, node: FallbackStart, ctx: ConverterContext):
        """
        kdl: `fallback <value>|{}`

        - в связке FallbackStart + FallbackEnd можно сделать try/catch
        - если в target отсутствует такая конструкция - эмулировать 
            - например, в golang через `defer func(){ rescue <value> }` + `panic`
        """
    @abstractmethod
    def visit_fallback_end(self, node: FallbackEnd, ctx: ConverterContext):
         """
        kdl: `fallback <value>|{}`

        - в связке FallbackStart + FallbackEnd можно сделать try/catch
        - если в target отсутствует такая конструкция - эмулировать 
            - например, в golang через `defer func(){ rescue <value> }` + `panic`
        """

    # === PREDICATE CALLS ===
    @abstractmethod
    def visit_filter(self, node: Filter, ctx: ConverterContext):
        """
        kdl: `filter { ... }`

        TYPES:
            - DOCUMENT[] -> DOCUMENT[]
            - STRING[] -> STRING[]

        - принимает тип DOCUMENT(array=true) | STRING(array=true)
        - фильтрует предикатами внутри, возвращает значения, которые дают true
        - для нескольких предикатов по умолчанию устанавливает AND
        """

    @abstractmethod
    def visit_assert(self, node: Assert, ctx: ConverterContext):
        """
        kdl: `assert { ... }`

        TYPES:
            - AUTO -> AUTO

        - фильтрует предикатами внутри
        - если значение false - вызывает ошибку
        - для нескольких предикатов по умолчанию устанавливает AND
        """

    @abstractmethod
    def visit_match(self, node: Match, ctx: ConverterContext):
        """
        kdl: `match { ... }`

        TYPES:
            - STRING -> STRING

        - специальная конструкция для полей в StructTable
        - тип STRING
        - фильтрует предикатами внутри
        - для нескольких предикатов по умолчанию устанавливает AND

        """

    # === LOGICAL ===
    @abstractmethod
    def visit_logic_and(self, node: LogicAnd, ctx: ConverterContext):
        """
        kdl: `and { ... }`

        - in 'and' constuct - separate by logical AND 

        example

        ```
        and {a; b; c}
        ```
        equal:

        ```
        (a && b && c)
        ```
        """

    @abstractmethod
    def visit_logic_or(self, node: LogicOr, ctx: ConverterContext):
        """
        kdl: `or { ... }`

        - in 'or' constuct - separate by logical OR

        example:

        ```
        or {a; b; c }
        ```
        equal:

        ```
        (a || b || c)
        ```
        """

    @abstractmethod
    def visit_logic_not(self, node: LogicNot, ctx: ConverterContext):
        """
        kdl: `not { ... }`

        - invert predicate results inner

        example:

        ```
        not { a; b; c }
        not { or {a; b; c} }
        ```
        equal
        ```
        !(a && b && c) && !((a || b || c))
        ```
        """

    # === LOGIC SELECTORS ===
    @abstractmethod
    def visit_predicate_css(self, node: PredCss, ctx: ConverterContext):
        """
        kdl: `css <query>`

        TYPES:
            - DOCUMENT

        check by query

        example:
        ```
        e.select("a") // true if exists else false
        ```
        """

    @abstractmethod
    def visit_predicate_xpath(self, node: PredXpath, ctx: ConverterContext):
        """
        kdl: `xpath <query>`

        TYPES:
            - DOCUMENT

        check by query

        example:
        ```
        e.xpath("a") // true if exists else false
        ```
        """

    @abstractmethod
    def visit_predicate_has_attr(
        self, node: PredHasAttr, ctx: ConverterContext
    ):
        """
        kdl: `has-attr <attrs...>`

        TYPES:
            - DOCUMENT

        check by attr keys
        - if passed keys>1 - converted to any(...)

        example:
        ```
        has-attr "href" // e.get("href")
        has-attr "href" "src" // any(e.get(k) for k in ["href", "src"])
        ```
        """

    @abstractmethod
    def visit_predicate_attr_contains(
        self, node: PredAttrContains, ctx: ConverterContext
    ):
        """
        kdl: `attr-contains <key> <substr...>`

        TYPES:
            - DOCUMENT

        check if attr key contains substring
        - dont need check exists key 
        - multiple substr converted to any()
        examples:
        ```
        attr-contains "class" "btn-"
        // "btn-" in e["class"]
        ```

        ```
        attr-contains "class" "btn-" "select-"
        // any(v in e["class"] for v in ["btn-", "select-"])
        ```
        """

    @abstractmethod
    def visit_predicate_attr_starts(
        self, node: PredAttrStarts, ctx: ConverterContext
    ):
        """
        kdl: `attr-starts <key> <substr...>`

        TYPES:
            - DOCUMENT

        check if attr key starts substring
        - dont need check exists key 
        - multiple substr converted to any()
        examples:
        ```
        attr-starts "class" "btn-"
        // e["class"].startswith("btn-")
        ```

        ```
        attr-starts "class" "btn-" "select-"
        // any(e["class"].startswith(v) for v in ["btn-", "select-"])
        ```
        """

    @abstractmethod
    def visit_predicate_attr_ends(
        self, node: PredAttrEnds, ctx: ConverterContext
    ):
        """
        kdl: `attr-ends <key> <substr...>`

        TYPES:
            - DOCUMENT

        check if attr key ends substring
        - dont need check exists key 
        - multiple substr converted to any()
        examples:
        ```
        attr-starts "class" "btn-"
        // e["class"].endswith("btn-")
        ```

        ```
        attr-starts "class" "btn-" "select-"
        // any(e["class"].endswith(v) for v in ["btn-", "select-"])
        ```
        """

    @abstractmethod
    def visit_predicate_attr_eq(self, node: PredAttrEq, ctx: ConverterContext):
        """
        kdl:`attr-eq <key> <value...>`

        TYPES:
            - DOCUMENT

        check if attr key equal value
        - dont need check exists key 
        - multiple substr converted to any()
        examples:
        ```
        attr-eq "class" "btn"
        // e["class"] == "btn"
        ```

        ```
        attr-eq "class" "btn" "select"
        // any(e["class"] == v for v in ["btn-", "select-"])
        ```

        """

    @abstractmethod
    def visit_predicate_attr_ne(self, node: PredAttrNe, ctx: ConverterContext):
        """
        kdl:`attr-ne <key> <value...>`

        TYPES:
            - DOCUMENT

        check if attr key equal value
        - dont need check exists key 
        - multiple substr converted to all()
        examples:
        ```
        attr-eq "class" "btn"
        // e["class"] != "btn"
        ```

        ```
        attr-eq "class" "btn" "select"
        // all(e["class"] != v for v in ["btn-", "select-"])
        """
    
    @abstractmethod
    def visit_predicate_attr_re(self, node: PredAttrRe, ctx: ConverterContext):
        """
        kdl:`attr-re <key> <pattern>`

        TYPES:
            - DOCUMENT

        check if attr key match by regex
        - dont need check exists key 

        example:

        ```
        attr-re "href" "\\d+"
        // e["href"].test("\\d+")
        ```
        """

    @abstractmethod
    def visit_predicate_text_contains(
        self, node: PredTextContains, ctx: ConverterContext
    ):
        """
        kdl:`text-contains <value...>`

        TYPES:
            - DOCUMENT

        check if element text contains substr
        - multiple substr converted to any()

        example:

        ```
        text-contains "docs"
        // "docs" in e.text
        ```

        ```
        text-contains "docs" "foo"
        // any(v in e.text for v in ["docs", "foo"]) 
        ```
        """

    @abstractmethod
    def visit_predicate_text_starts(
        self, node: PredTextStarts, ctx: ConverterContext
    ):
        """
        kdl:`text-starts <value...>`

        TYPES:
            - DOCUMENT

        check if element text starts substr
        - multiple substr converted to any()

        example:

        ```
        text-starts "docs"
        // e.text.startswith("docs")
        ```

        ```
        text-starts "docs" "foo"
        // any(e.text.startswith(v) for v in ["docs", "foo"]) 
        ```
        """

    @abstractmethod
    def visit_predicate_text_ends(
        self, node: PredTextEnds, ctx: ConverterContext
    ):
        """
        kdl:`text-ends <value...>`

        TYPES:
            - DOCUMENT

        check if element text ends substr
        - multiple substr converted to any()

        example:

        ```
        text-ends "docs"
        // e.text.endswith("docs")
        ```

        ```
        text-ends "docs" "foo"
        // any(e.text.endswith(v) for v in ["docs", "foo"]) 
        ```
        """

    @abstractmethod
    def visit_predicate_text_re(self, node: PredTextRe, ctx: ConverterContext):
        """
        kdl:`text-re <pattern>`

        TYPES:
            - DOCUMENT

        check if element text match pattern

        example:

        ```
        text-re "\\d+"
        // e.text.test("\\d+")
        ```
        """

    # === LOGIC STRING ===
    @abstractmethod
    def visit_predicate_contains(
        self, node: PredContains, ctx: ConverterContext
    ):
        """
        kdl:`contains <value...>`

        TYPES:
            - STRING

        check if string contains value(s)
        - multiple substr converted to any()

        examples:
        ```
        contains "a"
        // "a" in e
        ```

        ```
        contains "a" "b"
        // any(v in e for v in ["a", "b"])
        ```
        """

    @abstractmethod
    def visit_predicate_eq(self, node: PredEq, ctx: ConverterContext):
        """
        kdl:`eq <value...>`

        TYPES:
            - STRING

        check if string equal value(s)
        - if passed single integer - compare by len
        - multiple substr converted to any()

        examples:
        ```
        eq "a"
        // e == "a"
        ```

        ```
        eq 10
        // len(e) == 10
        ```

        ```
        eq "a" "b"
        // any(e == v for v in ["a", "b"])
        ```
        """

    @abstractmethod
    def visit_predicate_ne(self, node: PredNe, ctx: ConverterContext):
        """
        kdl:`ne <value...>`

        TYPES:
            - STRING

        check if string contains value(s)
        - if passed single integer - compare by len
        - multiple substr converted to all()

        examples:
        ```
        ne "a"
        // e != "a"
        ```

        ```
        ne 10
        // len(e) != 10
        ```

        ```
        ne "a" "b"
        // all(v in e for v in ["a", "b"])
        ```
        """

    @abstractmethod
    def visit_predicate_starts(self, node: PredStarts, ctx: ConverterContext):
        """
        kdl:`starts <values...>`

        TYPES:
            - STRING

        check if string starts value(s)
        - multiple values converted to any()

        examples:
        ```
        starts "foo"
        // e.startswith("foo")
        starts "foo" "bar"
        // any(e.startswith(v) for v in ["foo", "bar"])
        ```
        """

    @abstractmethod
    def visit_predicate_ends(self, node: PredEnds, ctx: ConverterContext):
        """
        kdl:`ends <values...>`

        TYPES:
            - STRING

        check if string ends value(s)
        - multiple values converted to any()

        examples:
        ```
        ends "foo"
        // e.endswith("foo")
        ends "foo" "bar"
        // any(e.endswith(v) for v in ["foo", "bar"])
        ```
        """

    @abstractmethod
    def visit_predicate_re(self, node: PredRe, ctx: ConverterContext):
        """
        kdl:`re <pattern>`

        TYPES:
            - STRING

        check string pattern match

        example:

        ```
        re "\\d+"
        // e.test("\\d+")
        ```
        """

    # TODO: remove: dup expr with contains <values...>
    def visit_predicate_in(self, node: PredIn, ctx: ConverterContext):
        """
        kdl:`in <values...>`
        """
        
    @abstractmethod
    def visit_predicate_ge(self, node: PredGe, ctx: ConverterContext):
        # TODO: remove, use len-ge
        """
        kdl:`ge`

        - `>=`
        - used in `assert` only expr
        - compare by len (string or array-like expr)
        """

    @abstractmethod
    def visit_predicate_gt(self, node: PredGt, ctx: ConverterContext):
        # TODO: remove, use len-gt
        """
        kdl:`gt`
        
        - `>`
        - used in `assert` only expr
        - compare by len (string or array-like expr)
        """

    @abstractmethod
    def visit_predicate_le(self, node: PredLe, ctx: ConverterContext):
        # TODO: remove, use len-le
        """
        kdl:`le`

        - `<=`
        - used in `assert` only expr
        - compare by len (string or array-like expr)
        """

    @abstractmethod
    def visit_predicate_lt(self, node: PredLt, ctx: ConverterContext):
        # TODO: remove, use len-lt
        """
        kdl:`lt`

        `<`
        - used in `assert` only expr
        - compare by len (string or array-like expr)
        """

    # === logic len ===
    @abstractmethod
    def visit_predicate_re_all(self, node: PredReAll, ctx: ConverterContext):
        """
        kdl:`re-all <pattern>`

        TYPES:
            - STRING[] -> STRING[]

        - accept STRING(array=true)
        - should be all strings matched by pattern
        """

    @abstractmethod
    def visit_predicate_re_any(self, node: PredReAny, ctx: ConverterContext):
        """
        kdl:`re-any <pattern>`

        TYPES:
            - STRING[] -> STRING[]

        - accept STRING(array=true)
        - should be any string matched by pattern
        """

    @abstractmethod
    def visit_predicate_count_eq(
        self, node: PredCountEq, ctx: ConverterContext
    ):
        """
        kdl:`len-eq <N>`

        TYPES:
            - AUTO[] -> AUTO[]
            - STRING -> STRING

        - len ==
        """

    @abstractmethod
    def visit_predicate_count_ne(
        self, node: PredCountNe, ctx: ConverterContext
    ):
        """
        kdl:`len-ne`

        TYPES:
            - AUTO[] -> AUTO[]
            - STRING -> STRING

        - len !=
        """

    @abstractmethod
    def visit_predicate_count_gt(
        self, node: PredCountGt, ctx: ConverterContext
    ):
        """
        kdl:`len-gt`

        TYPES:
            - AUTO[] -> AUTO[]
            - STRING -> STRING

        - len >
        """

    @abstractmethod
    def visit_predicate_count_lt(
        self, node: PredCountLt, ctx: ConverterContext
    ):
        """
        kdl:`len-lt <N>`

        TYPES:
            - AUTO[] -> AUTO[]
            - STRING -> STRING

        - len <
        """

    @abstractmethod
    def visit_predicate_count_ge(
        self, node: PredCountGe, ctx: ConverterContext
    ):
        """
        kdl:`len-ge`

        TYPES:
            - AUTO[] -> AUTO[]
            - STRING -> STRING

        - len >=
        """

    @abstractmethod
    def visit_predicate_count_le(
        self, node: PredCountLe, ctx: ConverterContext
    ):
        """
        kdl:`len-le`

        TYPES:
            - AUTO[] -> AUTO[]
            - STRING -> STRING

        - len <=
        """

    @abstractmethod
    def visit_pred_count_range(
        self, node: PredCountRange, ctx: ConverterContext
    ):
        """
        kdl:`len-range <start> <end>`

        TYPES:
            - AUTO[] -> AUTO[]
            - STRING -> STRING

        - START > len > END
        """
