# Auto generated code by ssc_gen
# WARNING: Any manual changes made to this file will be lost when this
# is run again. Do not edit this file unless you know what you are doing.

from __future__ import annotations  # python 3.7, 3.8 comp
import re
from typing import Any, Union, List

from selectolax.parser import HTMLParser, Node

_T_DICT_ITEM = dict[str, Union[str, list[str]]]
_T_LIST_ITEMS = list[dict[str, Union[str, list[str]]]]


class _BaseStructParser:
    # TODO: add kwargs for config selector
    def __init__(self, document: str):
        self.__raw__ = document
        self.__selector__ = HTMLParser(document)
        self._cached_result: Union[_T_DICT_ITEM, _T_LIST_ITEMS] = {}

    def _pre_validate(self, document: HTMLParser) -> None:
        # pre validate entrypoint, contain assert expressions
        pass

    def parse(self):
        """run parser"""
        self._pre_validate(self.__selector__)
        self._start_parse()
        return self

    def view(self) -> Union[_T_DICT_ITEM, _T_LIST_ITEMS]:
        """get parsed values"""
        return self._cached_result

    def _start_parse(self):
        """parse logic entrypoint"""
        pass


class Book(_BaseStructParser):
    def __init__(self, document: str):
        super().__init__(document)
        self._cached_result: _T_DICT_ITEM = {}

    def _pre_validate(self, doc: HTMLParser) -> None:
        var_0 = doc
        var_1 = var_0.css_first("title")
        var_2 = var_1.text()
        assert "Books to Scrape - Sandbox" in var_2
        return

    def _start_parse(self):
        self._cached_result.clear()
        self._cached_result["description"] = self._parse_description(
            self.__selector__
        )
        self._cached_result["title"] = self._parse_title(self.__selector__)
        self._cached_result["price"] = self._parse_price(self.__selector__)
        self._cached_result["upc"] = self._parse_upc(self.__selector__)
        self._cached_result["raw_table_values"] = self._parse_raw_table_values(
            self.__selector__
        )

    def view(self) -> _T_DICT_ITEM:
        return self._cached_result

    def _parse_description(self, doc: HTMLParser):
        """product description"""

        var_0 = doc
        var_1 = var_0.css_first("#content_inner > article > p")
        var_2 = var_1.text()
        return var_2

    def _parse_title(self, doc: HTMLParser):
        var_0 = doc
        var_1 = var_0.css_first("h1")
        var_2 = var_1.text()
        return var_2

    def _parse_price(self, doc: HTMLParser):
        var_0 = doc
        try:
            var_2 = var_0.css_first(".product_main .price_color")
            var_3 = var_2.text()
        except Exception as e:
            return "0"
        return var_3

    def _parse_upc(self, doc: HTMLParser):
        var_0 = doc
        var_1 = var_0.css_first("tr:nth-child(1) td")
        var_2 = var_1.text()
        return var_2

    def _parse_raw_table_values(self, doc: HTMLParser):
        var_0 = doc
        var_1 = var_0.css("tr > td")
        var_2 = [el.text() for el in var_1]
        var_3 = [s.strip(" ") for s in var_2]
        return var_3


class BooksCatalogue(_BaseStructParser):
    """parse books from catalogue"""

    def __init__(self, document: str):
        super().__init__(document)
        self._cached_result: _T_LIST_ITEMS = []

    def _pre_validate(self, doc: HTMLParser) -> None:
        var_0 = doc
        var_1 = var_0.css_first("title")
        var_2 = var_1.text()
        assert "Books to Scrape - Sandbox" in var_2
        return

    def _part_document(self) -> List[Node]:
        doc = self.__selector__
        var_0 = doc
        var_1 = var_0.css(".col-lg-3")
        return var_1

    def _start_parse(self):
        self._cached_result.clear()
        for part in self._part_document():
            self._cached_result.append(
                {
                    "url": self._parse_url(part),
                    "title": self._parse_title(part),
                    "price": self._parse_price(part),
                    "image": self._parse_image(part),
                    "rating": self._parse_rating(part),
                }
            )

    def view(self) -> _T_LIST_ITEMS:
        return self._cached_result

    def _parse_url(self, doc: Node):
        """page url to product"""

        var_0 = doc
        var_1 = var_0.css_first("h3 > a")
        var_2 = var_1.attributes["href"]
        var_3 = "https://books.toscrape.com/catalogue/{}".format(var_2)
        return var_3

    def _parse_title(self, doc: Node):
        var_0 = doc
        var_1 = var_0.css_first("h3 > a")
        var_2 = var_1.attributes["title"]
        return var_2

    def _parse_price(self, doc: Node):
        var_0 = doc
        try:
            var_2 = var_0.css_first(".price_color")
            var_3 = var_2.text()
            var_4 = var_3.lstrip("£")
        except Exception as e:
            return "0"
        return var_4

    def _parse_image(self, doc: Node):
        var_0 = doc
        var_1 = var_0.css_first("img.thumbnail")
        var_2 = var_1.attributes["src"]
        var_3 = var_2.lstrip("..")
        var_4 = "https://books.toscrape.com{}".format(var_3)
        return var_4

    def _parse_rating(self, doc: Node):
        var_0 = doc
        var_1 = var_0.css_first(".star-rating")
        var_2 = var_1.attributes["class"]
        var_3 = var_2.lstrip("star-rating ")
        return var_3
