"""Python base runtime constants and helpers."""

_BASE_UTILITY_LINES: list[str] = [
    "_RE_HEX_ENTITY = re.compile(r'&#x([0-9a-fA-F]+);')",
    "_RE_UNICODE_ENTITY = re.compile(r'\\\\u([0-9a-fA-F]{4})')",
    "_RE_BYTES_ENTITY = re.compile(r'\\\\x([0-9a-fA-F]{2})')",
    "_RE_CHARS_MAP = {'\\b': '\\b', '\\f': '\\f', '\\n': '\\n', '\\r': '\\r', '\\t': '\\t'}",
    "",
    "def repl_map(s: str, rmap: Dict[str, str]) -> str:",
    "    for k, v in rmap.items():",
    "        s = s.replace(k, v)",
    "    return s",
    "",
    "def normalize_text(text: str) -> str:",
    "    return ' '.join(text.split()) if text else \"\"",
    "",
    "class _UnmatchedTableRow:",
    "    pass",
    "",
    "def unescape_text(text: str) -> str:",
    "    s = ssc_html_unescape(text)",
    "    s = _RE_HEX_ENTITY.sub(lambda m: chr(int(m.group(1), 16)), s)",
    "    s = _RE_UNICODE_ENTITY.sub(lambda m: chr(int(m.group(1), 16)), s)",
    "    s = _RE_BYTES_ENTITY.sub(lambda m: chr(int(m.group(1), 16)), s)",
    "    for ch, r in _RE_CHARS_MAP.items():",
    "        s = s.replace(ch, r)",
    "    return s",
    "",
    "if sys.version_info >= (3, 9):",
    "    def rm_prefix(s: str, p: str) -> str:",
    "        return s.removeprefix(p)",
    "",
    "    def rm_suffix(s: str, p: str) -> str:",
    "        return s.removesuffix(p)",
    "",
    "else:",
    "    def rm_prefix(s: str, p: str) -> str:",
    "        return s[len(p):] if s.startswith(p) else s",
    "",
    "    def rm_suffix(s: str, p: str) -> str:",
    "        return s[:-(len(p))] if s.endswith(p) else s",
    "",
    "",
    "UNMATCHED_TABLE_ROW = _UnmatchedTableRow()",
]

_BASE_EXPORT_NAMES: list[str] = [
    "repl_map",
    "normalize_text",
    "_UnmatchedTableRow",
    "unescape_text",
    "rm_prefix",
    "rm_suffix",
    "UNMATCHED_TABLE_ROW",
]
