"""REST runtime assembly and runtime file registration."""

from collections.abc import Callable

from ssc_codegen.converters.base import BaseConverter

import ssc_codegen.ast as a

from ._helpers import _module_has_rest
from .py_base import _BASE_UTILITY_LINES, _BASE_EXPORT_NAMES


def rest_imports(module: a.Module) -> list[str]:
    if _module_has_rest(module):
        return [
            "from dataclasses import dataclass, field",
            "from typing import Generic, Literal, Mapping, TypeVar",
        ]
    return []


def rest_utilities(module: a.Module) -> list[str]:
    if not _module_has_rest(module):
        return []
    return [
        "_T = TypeVar('_T')",
        "_E = TypeVar('_E')",
        "\n",
        "@dataclass(frozen=True)",
        "class Ok(Generic[_T]):",
        "    status: int = 0",
        "    headers: Mapping[str, str] = field(default_factory=dict)",
        "    value: _T = None  # type: ignore[assignment]",
        "    is_ok: Literal[True] = True",
        "\n",
        "@dataclass(frozen=True)",
        "class Err(Generic[_E]):",
        "    status: int = 0",
        "    headers: Mapping[str, str] = field(default_factory=dict)",
        "    value: _E = None  # type: ignore[assignment]",
        "    is_ok: Literal[False] = False",
        "\n",
        "@dataclass(frozen=True)",
        "class UnknownErr(Err[Any]):",
        "    pass",
        "\n",
        "@dataclass(frozen=True)",
        "class TransportErr(Err[None]):",
        "    status: Literal[0] = 0",
        "    cause: str = ''",
        "    value: None = None",
        "    headers: Mapping[str, str] = field(default_factory=dict)",
        "\n\n",
        "def ssc_parse_response(_resp):",
        "    _status = _resp.status_code",
        "    _headers = {k.lower(): v for k, v in _resp.headers.items()}",
        "    try:",
        "        _body = _resp.json()",
        "    except Exception:",
        "        _body = None",
        "    return _status, _headers, _body",
        "\n\n",
    ]


def runtime_export_names(module: a.Module) -> list[str]:
    names = list(_BASE_EXPORT_NAMES)
    if _module_has_rest(module):
        names.extend(
            ["Ok", "Err", "UnknownErr", "TransportErr", "ssc_parse_response"]
        )
    return names


def runtime_module_content(module: a.Module) -> str:
    lines: list[str] = [
        "# autogenerated runtime helpers — do not edit",
        "import re",
        "import sys",
        "from typing import Dict",
        "from html import unescape as ssc_html_unescape",
    ]
    has_rest = _module_has_rest(module)
    if has_rest:
        lines.extend(
            [
                "from dataclasses import dataclass, field",
                "from typing import Any, Generic, Literal, Mapping, TypeVar",
            ]
        )
    lines.append("")
    lines.append("")
    lines.extend(_BASE_UTILITY_LINES)
    lines.append("")
    if has_rest:
        lines.extend(rest_utilities(module))
    return "\n".join(lines)


def register_runtime_file(
    converter: BaseConverter,
    runtime_name: str = "sscgen_runtime",
    *,
    include_fallback: bool = False,
) -> Callable[[list[a.Module]], str]:
    """Register a runtime module file provider on the converter.

    Returns a callable ``generate_runtime(modules) -> str`` that produces
    the runtime file content for a list of parsed modules, picking the one
    with REST structs as the reference AST automatically.
    """

    def _apply_fallback(content: str) -> str:
        if not include_fallback:
            return content
        return content.replace(
            "_RE_HEX_ENTITY",
            'FALLBACK_HTML_STR = "<html><body></body></html>"\n\n_RE_HEX_ENTITY',
            1,
        )

    @converter.file(f"{runtime_name}.py")
    def _runtime_provider(module_ast: a.Module, meta):
        return _apply_fallback(runtime_module_content(module_ast))

    def _generate_runtime(modules: list[a.Module]) -> str:
        ref = next(
            (m for m in modules if _module_has_rest(m)),
            modules[0],
        )
        return _apply_fallback(runtime_module_content(ref))

    return _generate_runtime
