"""helper function for templates"""
from typing import TYPE_CHECKING
import re

if TYPE_CHECKING:
    from src.yaml_parser import Info


def camelcase(s: str) -> str:
    return "".join(word[0].upper() + word[1:] for word in s.split("_"))


def snake_case(s: str) -> str:
    return re.sub(r"(?<!^)(?=[A-Z])", "_", s).lower()


def generate_meta_info(info: "Info") -> str:
    return f"""Auto generated code by selector_schema_codegen

id: {info.id}
name: {info.name}
author: {info.author}
description:
    {info.description}
source: {info.source}
tags:
    {info.tags}

WARNING: Any manual changes made to this file will be lost when this
is run again. Do not edit this file unless you know what you are doing.
"""
