"""Shared Rust runtime emitted beside generated parser modules."""

from __future__ import annotations


RUST_RUNTIME = r"""// Code generated by ssc-gen. DO NOT EDIT.
use dom_query::{Document, NodeId, NodeRef, Selection};
use regex::Regex;
use serde::de::DeserializeOwned;
use serde_json::Value;
use std::cell::RefCell;
use std::collections::HashSet;
use std::fmt;
use std::rc::Rc;

pub type Dom = Rc<RefCell<Document>>;
pub type Nodes = Vec<NodeId>;

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SscError {
    pub context: String,
    pub message: String,
}

impl SscError {
    pub fn new(context: impl Into<String>, message: impl Into<String>) -> Self {
        Self { context: context.into(), message: message.into() }
    }
}

impl fmt::Display for SscError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        if self.context.is_empty() { write!(f, "{}", self.message) }
        else { write!(f, "{}: {}", self.context, self.message) }
    }
}

impl std::error::Error for SscError {}

pub fn root_id(dom: &Dom) -> NodeId { dom.borrow().root().id }
pub fn first_node(nodes: &Nodes, context: &str) -> Result<NodeId, SscError> {
    nodes.first().copied().ok_or_else(|| SscError::new(context, "value has no selected node"))
}
pub fn node_at(nodes: &Nodes, index: i64, context: &str) -> Result<Nodes, SscError> {
    let pos = if index < 0 { nodes.len() as i64 + index } else { index };
    nodes.get(pos as usize).copied().map(|id| vec![id])
        .ok_or_else(|| SscError::new(context, "index out of bounds"))
}
pub fn string_at(values: &[String], index: i64, context: &str) -> Result<String, SscError> {
    let pos = if index < 0 { values.len() as i64 + index } else { index };
    values.get(pos as usize).cloned().ok_or_else(|| SscError::new(context, "index out of bounds"))
}

fn select_from<'a>(doc: &'a Document, root: NodeId, query: &str) -> Selection<'a> {
    if root == doc.root().id { doc.select(query) }
    else { Selection::from(NodeRef::new(root, &doc.tree)).select(query) }
}

pub fn select(dom: &Dom, roots: &Nodes, queries: &[&str], context: &str) -> Result<Nodes, SscError> {
    let doc = dom.borrow();
    for query in queries {
        let mut out = Vec::new();
        if roots.is_empty() { continue; }
        for root in roots {
            out.extend(select_from(&doc, *root, query).nodes().iter().map(|n| n.id));
        }
        if !out.is_empty() { return Ok(out); }
    }
    Err(SscError::new(context, "selector matched no elements"))
}

pub fn select_all(dom: &Dom, roots: &Nodes, queries: &[&str], context: &str) -> Result<Nodes, SscError> {
    let doc = dom.borrow();
    for query in queries {
        let mut out = Vec::new();
        for root in roots {
            out.extend(select_from(&doc, *root, query).nodes().iter().map(|n| n.id));
        }
        if !out.is_empty() { return Ok(out); }
    }
    Ok(Vec::new())
}

pub fn remove(dom: &Dom, roots: &Nodes) -> Result<Nodes, SscError> {
    let doc = dom.borrow();
    for id in roots { NodeRef::new(*id, &doc.tree).remove_from_parent(); }
    Ok(roots.clone())
}

pub fn text(dom: &Dom, roots: &Nodes, context: &str) -> Result<String, SscError> {
    let doc = dom.borrow();
    roots.first().map(|id| NodeRef::new(*id, &doc.tree).text().to_string())
        .ok_or_else(|| SscError::new(context, "value has no selected node"))
}

pub fn text_all(dom: &Dom, roots: &Nodes) -> Vec<String> {
    let doc = dom.borrow();
    roots.iter().map(|id| NodeRef::new(*id, &doc.tree).text().to_string()).collect()
}

pub fn raw(dom: &Dom, roots: &Nodes, inner: bool, context: &str) -> Result<String, SscError> {
    let doc = dom.borrow();
    roots.first().map(|id| {
        let node = NodeRef::new(*id, &doc.tree);
        if inner { node.inner_html().to_string() } else { node.html().to_string() }
    }).ok_or_else(|| SscError::new(context, "value has no selected node"))
}

pub fn raw_all(dom: &Dom, roots: &Nodes, inner: bool) -> Vec<String> {
    let doc = dom.borrow();
    roots.iter().map(|id| {
        let node = NodeRef::new(*id, &doc.tree);
        if inner { node.inner_html().to_string() } else { node.html().to_string() }
    }).collect()
}

pub fn attr(dom: &Dom, roots: &Nodes, names: &[&str], context: &str) -> Result<String, SscError> {
    let doc = dom.borrow();
    let node = roots.first().ok_or_else(|| SscError::new(context, "value has no selected node"))?;
    let node = NodeRef::new(*node, &doc.tree);
    names.iter().find_map(|name| node.attr(name).map(|v| v.to_string()))
        .ok_or_else(|| SscError::new(context, "attribute not found"))
}

pub fn attr_all(dom: &Dom, roots: &Nodes, names: &[&str]) -> Vec<String> {
    let doc = dom.borrow();
    roots.iter().filter_map(|id| {
        let node = NodeRef::new(*id, &doc.tree);
        names.iter().find_map(|name| node.attr(name).map(|v| v.to_string()))
    }).collect()
}

pub fn trim(value: String, chars: Option<&str>) -> String {
    chars.map_or_else(|| value.trim().to_string(), |c| value.trim_matches(|x| c.contains(x)).to_string())
}
pub fn ltrim(value: String, chars: Option<&str>) -> String {
    chars.map_or_else(|| value.trim_start().to_string(), |c| value.trim_start_matches(|x| c.contains(x)).to_string())
}
pub fn rtrim(value: String, chars: Option<&str>) -> String {
    chars.map_or_else(|| value.trim_end().to_string(), |c| value.trim_end_matches(|x| c.contains(x)).to_string())
}
pub fn normalize_space(value: String) -> String { value.split_whitespace().collect::<Vec<_>>().join(" ") }
pub fn rm_prefix(value: String, prefix: &str) -> String { value.strip_prefix(prefix).unwrap_or(&value).to_string() }
pub fn rm_suffix(value: String, suffix: &str) -> String { value.strip_suffix(suffix).unwrap_or(&value).to_string() }
pub fn rm_prefix_suffix(value: String, part: &str) -> String { rm_suffix(rm_prefix(value, part), part) }
pub fn fmt_value(template: &str, value: &str) -> String { template.replacen("{{}}", value, 1) }
pub fn repl(value: String, old: &str, new: &str) -> String { value.replace(old, new) }
pub fn lower(value: String) -> String { value.to_lowercase() }
pub fn upper(value: String) -> String { value.to_uppercase() }
pub fn unescape(value: String) -> String {
    value.replace("&amp;", "&").replace("&lt;", "<").replace("&gt;", ">")
        .replace("&quot;", "\"").replace("&#39;", "'")
}

pub fn index(value: &str, index: i64, context: &str) -> Result<String, SscError> {
    let chars: Vec<char> = value.chars().collect();
    let pos = if index < 0 { chars.len() as i64 + index } else { index };
    chars.get(pos as usize).copied().map(|c| c.to_string())
        .ok_or_else(|| SscError::new(context, "index out of bounds"))
}
pub fn slice(value: &str, start: i64, end: i64) -> String {
    let chars: Vec<char> = value.chars().collect();
    let len = chars.len() as i64;
    let normalize = |n: i64| if n < 0 { (len + n).max(0) } else { n.min(len) };
    let start = normalize(start);
    let end = normalize(end);
    if start >= end { return String::new(); }
    chars[start as usize..end as usize].iter().collect()
}
pub fn slice_vec<T: Clone>(value: &[T], start: i64, end: i64) -> Vec<T> {
    let len = value.len() as i64;
    let normalize = |n: i64| if n < 0 { (len + n).max(0) } else { n.min(len) };
    let start = normalize(start);
    let end = normalize(end);
    if start >= end { Vec::new() } else { value[start as usize..end as usize].to_vec() }
}
pub fn unique(value: Vec<String>) -> Vec<String> {
    let mut seen = HashSet::new(); let mut out = Vec::new();
    for item in value { if seen.insert(item.clone()) { out.push(item); } } out
}
pub fn to_int(value: String, context: &str) -> Result<i64, SscError> { value.trim().parse().map_err(|e| SscError::new(context, format!("invalid integer: {e}"))) }
pub fn to_float(value: String, context: &str) -> Result<f64, SscError> { value.trim().parse().map_err(|e| SscError::new(context, format!("invalid float: {e}"))) }
pub fn assert_true(value: bool, context: &str) -> Result<(), SscError> { if value { Ok(()) } else { Err(SscError::new(context, "assertion failed")) } }

pub fn regex_search(value: String, pattern: &str, context: &str) -> Result<String, SscError> {
    let re = Regex::new(pattern).map_err(|e| SscError::new(context, e.to_string()))?;
    let captures = re.captures(&value).ok_or_else(|| SscError::new(context, "regex did not match"))?;
    Ok(captures.get(1).or_else(|| captures.get(0)).unwrap().as_str().to_string())
}
pub fn regex_all(value: String, pattern: &str, context: &str) -> Result<Vec<String>, SscError> {
    let re = Regex::new(pattern).map_err(|e| SscError::new(context, e.to_string()))?;
    Ok(re.captures_iter(&value).map(|c| c.get(1).or_else(|| c.get(0)).unwrap().as_str().to_string()).collect())
}
pub fn regex_sub(value: String, pattern: &str, replacement: &str, context: &str) -> Result<String, SscError> {
    let re = Regex::new(pattern).map_err(|e| SscError::new(context, e.to_string()))?;
    Ok(re.replace_all(&value, replacement).into_owned())
}

pub fn json_path<'a>(value: &'a Value, path: &str, context: &str) -> Result<&'a Value, SscError> {
    if path.is_empty() { return Ok(value); }
    let mut current = value;
    for segment in path.split('.') {
        current = (if let Ok(index) = segment.parse::<usize>() {
            current.get(index)
        } else { current.get(segment) })
            .ok_or_else(|| SscError::new(context, format!("missing JSON path segment '{segment}'")))?;
    }
    Ok(current)
}
pub fn parse_json(value: &str, path: &str, context: &str) -> Result<Value, SscError> {
    let parsed: Value = serde_json::from_str(value).map_err(|e| SscError::new(context, e.to_string()))?;
    Ok(json_path(&parsed, path, context)?.clone())
}
pub fn decode<T: DeserializeOwned>(value: Value, context: &str) -> Result<T, SscError> {
    serde_json::from_value(value).map_err(|e| SscError::new(context, e.to_string()))
}

pub fn node_bool(value: &Nodes) -> bool { !value.is_empty() }
pub fn string_bool(value: &str) -> bool { !value.is_empty() }
pub fn contains(value: &str, needle: &str) -> bool { value.contains(needle) }
pub fn starts(value: &str, needle: &str) -> bool { value.starts_with(needle) }
pub fn ends(value: &str, needle: &str) -> bool { value.ends_with(needle) }
pub fn regex_match(value: &str, pattern: &str) -> bool { Regex::new(pattern).map(|r| r.is_match(value)).unwrap_or(false) }
pub fn pred_css(dom: &Dom, roots: &Nodes, query: &str) -> bool {
    let doc = dom.borrow(); roots.iter().any(|id| !select_from(&doc, *id, query).is_empty())
}
pub fn pred_attr(dom: &Dom, roots: &Nodes, name: &str) -> Option<String> {
    let doc = dom.borrow(); roots.first().and_then(|id| NodeRef::new(*id, &doc.tree).attr(name).map(|v| v.to_string()))
}
pub fn pred_text(dom: &Dom, roots: &Nodes) -> String { text_all(dom, roots).join("") }
"""


def rust_runtime_content(
    extra_imports: list[str] | None = None, helpers: list[str] | None = None
) -> str:
    """Return the shared Rust runtime source with extension helpers appended."""
    source = RUST_RUNTIME
    if extra_imports:
        marker = "use std::rc::Rc;\n"
        source = source.replace(
            marker, marker + "".join(f"{line}\n" for line in extra_imports), 1
        )
    if helpers:
        source += "\n" + "\n\n".join(helpers) + "\n"
    return source
